deployment/deployment1.json, deployment/deployment1v1beta3.json, deployment/manual.json, deployment/post.json, deployment/postv1beta3.json, deployment/pre.json, deployment/prev1beta3.json, deployment/rollback1.json, deployment/rollback2.json, deployment/rollback3.json, deployment/rollback4.json, deployment/sleepv1.json, deployment/testhook.json, deployment/updatev1.json
=> Add deployment testing json files

build/README.md, image/README.md
Please kindly review and help to merge, thanks!
=> Create build and image folder for devexp team

pods/pod_with_two_containers.json
Add a json file to pods directory, this file is used to create a POD with two containers using different images
=> adding testing pod json file

cli/replication-controller-match-a-service.yaml
Add a testing file which is used to create a RC that matches a service
=> Adding testing rc files

build/application-template-wildfly.json, build/sample-php-centos7.json, build/sample-php-rhel7.json, image/db-templates/mongodb-24-centos7-env-test.json, image/db-templates/mongodb-24-rhel7-env-test.json, image/db-templates/mongodb-24-rhel7-template.json, image/db-templates/mysql-55-rhel7-template.json, image/db-templates/postgresql-92-centos7-env-test.json, image/db-templates/postgresql-92-rhel7-env-test.json, image/db-templates/postgresql-92-rhel7-template.json, image/language-image-templates/php-55-centos7-stibuild.json, image/language-image-templates/php-55-rhel7-stibuild.json
Test files added for image and build test
=> Test files added for image and build test

build/stibuild-configchange-trigger.sjon, build/stibuild-generic-trigger.json, build/stibuild-github-trigger.json, build/stibuild-imagechange-trigger.json
For some auto test, need separate different trigger type for bc.
If use the default application-template-stibuild.json, a new build is auto generated when create app.
=> separate different trigger type for buildConfig

build/custom-build-invalid.json
Added on testfile about use invalid build strategy
=> add invalid custom file

image/db-templates/mysql-55-env-var-test.json
HI, I added a test file about mysql env var test, could you please review and merge? Thanks!
=> add mysql env var test file

pods/hello-pod-bad.json
Added bad pod json file for TCMS case #472860.
=> Added bad pod json file for TCMS case #472860.

image-streams/extra-image-streams-rhel7.json
update extra-image-streams-rhel7.json file, pls merge to master ,thx
=> update extra-image-streams-rhel7.json file

templates/tc476356/application-template-dockerbuild.json, templates/tc476357/application-template-stibuild.json
template json files for tc 476357 and 476356 for automating
=> template json files for tc 476357 and 476356

deployment/manual.json
please help merge the fix. thanks.
=> fix deployment/manual.json file according the bug1258724

image-streams/image-streams-aep.json
Hi, I have create image stream file for image test in AEP, please review and merge if no issues. Thanks!
=> Create image stream for aep test

deployment/tc489264/deployment-test.json
=> json file for tc489264

deployment/tc472859/hello-pod.json
get a pod in a pending state forever to catch the pending state for
sure.
=> tc472895 template file

image-streams/extra-image-streams-centos7.json, image-streams/extra-image-streams-rhel7.json, image/db-templates/mongodb-26-centos7-env-test.json, image/db-templates/mongodb-26-rhel7-env-test.json, image/db-templates/postgresql-94-centos7-env-test.json, image/db-templates/postgresql-94-rhel7-env-test.json, image/db-templates/postgresql-replica-centos7.json, image/db-templates/postgresql-replica-rhel7.json
update some imagestream files, please help to merge ,thank you
=> update some imagestream files

templates/tc499484/php-55-centos7-stibuild.json
Added template for TCMS scenario #499484.
=> Added template for TCMS scenario #499484.

templates/tc499621/python-27-rhel7.json
Added template for TCMS scenario 499621.
=> Added template for TCMS scenario 499621.

image/db-templates/mongodb-26-rhel7-env-test.json, image/db-templates/mysql-56-rhel7-env-var-test.json
Hi, I have updated image registry for some images, could you please review and merge? Thanks!
=> Update image registry

image/db-templates/nodejs-template-stibuild.json, image/language-image-templates/python-27-rhel7-stibuild.json, image/language-image-templates/python-27-rhel7.json
add some test cases file for automation easily ,please help to merge ,thx
=> add some test cases file

templates/tc499621/python-27-rhel7.json
Updated template for tcms case #499621
=> Updated template for tcms case #499621

image/language-image-templates/python-27-centos7-stibuild.json
add python27 files for automation,help to merge ,thx
=> add python27 files for automation

image/language-image-templates/python-27-rhel7-context-stibuild.json, image/language-image-templates/python-27-rhel7-errordir-stibuild.json
add two python files for testing ,please to merge ,thx
=> add two python files for testing

build/sample-php-rhel7.json, build/sourcebuildconfig.json, image/language-image-templates/php-55-rhel7-stibuild.json, image/language-image-templates/php-56-rhel7-stibuild.json
Hi, I have update some template and added new templates, could you please review and merge? Thanks!
=> Update some template and add new template

build/ruby20rhel7-template-sti.json, build/ruby20rhel7-tesmplate-docker.json, build/ruby22rhel7-template-sti.json, build/ruby22rhel7-tesmplate-docker.json
=> Add ruby rhel7 templates

image/db-templates/nodejs-template-stibuild.json
=> update version to v1

build/php55-imageupgrade-stibuild.json, build/php56-imageupgrade-stibuild.json
I added two template for image update test, please kindly review and merge, thanks!
=> add template for image update test

build/python27-imageupgrade-stibuild.json, build/python33-imageupgrade-stibuild.json, build/python34-imageupgrade-stibuild.json, image-streams/extra-image-streams-centos7.json, image-streams/extra-image-streams-rhel7.json
add imageupgrade files for new cases ,pls merge ,thx
=> add imageupgrade files

persistent-volumes/fc/claim-rox.json, persistent-volumes/fc/claim-rwo.json, persistent-volumes/fc/claim-rwx.json, persistent-volumes/fc/pod.json, persistent-volumes/fc/pv-default-rox.json, persistent-volumes/fc/pv-recycle-rwo.json, persistent-volumes/fc/pv-retain-rwx.json
add persistent storage test files for fibrechannel (case 510354, 510355, 510356)
=> add persistent storage test files for fibrechannel

build/perl516-imageupgrade-stibuild.json, build/perl520-imageupgrade-stibuild.json, build/ruby20rhel7-tesmplate-docker.json, build/ruby22-imageupgrade-stibuild.json, build/ruby22rhel7-tesmplate-docker.json, image-streams/jboss-upgrade-image-stream.json
v1beta3 will be disabled soon, so update files
=> Modify template version

templates/tc484487/jboss-image-streams.json, templates/tc484487/jws-tomcat7-mysql-sti.json
=> Added new files for tc484487.

persistent-volumes/fc/pv-default-rox.json, persistent-volumes/fc/pv-recycle-rwo.json, persistent-volumes/fc/pv-retain-rwx.json
correct format of fibrechannel json files
=> correct format

image-streams/extra-image-streams-rhel7.json, image-streams/python27-image-stream-rhel7.json, image/db-templates/mongodb-clustered.json, image/db-templates/nodejs-template-stibuild.json, image/language-image-templates/python-33-centos7-var.json, image/language-image-templates/python-33-rhel7-var.json, image/language-image-templates/template_onbuild.json
add 2 python files for testing environment variables, pls help to merge ,thx
=> add 2 python files for testing environment variables

templates/tc497403/replication-controller-match-a-service.yaml
Added template for TCMS case #497403.
=> Added template for TCMS case #497403.

persistent-volumes/nfs/template-pv.json, persistent-volumes/nfs/template-pvc.json
Testing files for pv/pvc race bind.
=> add template file for pv and pvc

image/language-image-templates/application-template-dockerbuild-var0.json, image/language-image-templates/application-template-dockerbuild-vars.json, image/language-image-templates/python-33-rhel7-var.json
update some files for python var testing ,pls help to merge thx
=> update some files for python var testing

build/sample-php-rhel7.json, image/db-templates/mysql-56-env-var-test.json, image/language-image-templates/php-55-rhel7-stibuild.json
I have updated some json files, please help to merge, thanks!
=> Update some files

build/ruby20rhel7-template-sti.json
=> update to use imagestream under openshift

build/ruby20rhel7-context-docker.json
=> Create test file for case 438849

image/language-image-templates/nodejs-template-stibuild.json, image/language-image-templates/python-27-rhel7-context-stibuild.json, image/language-image-templates/python-27-rhel7-errordir-stibuild.json, image/language-image-templates/python-27-rhel7-stibuild.json, image/language-image-templates/python-27-rhel7.json, image/language-image-templates/python-33-rhel7-var.json, image/language-image-templates/python-34-rhel7-stibuild.json
update  imagestreams version for detail tags, pls help to merge,thx
=> update  imagestreams version for detail tags

build/perl516rhel7-env-sti.json, build/ruby20rhel7-env-sti.json, build/ruby20rhel7-template-docker.json, build/ruby22rhel7-template-docker.json
=> Add test file for cases 499491 and 499488

build/sample-php-centos7.json, build/sample-php-rhel7.json, build/sourcebuildconfig.json, image/db-templates/nodejs-template-stibuild.json, image/language-image-templates/nodejs-template-stibuild.json, image/language-image-templates/php-55-centos7-stibuild.json, image/language-image-templates/php-55-rhel7-stibuild.json, image/language-image-templates/php-56-rhel7-stibuild.json, templates/tc497680/nodejs-template-stibuild.json, templates/tc499484/php-55-centos7-stibuild.json
=> Change private account to public one

image/language-image-templates/python-27-rhel7-var.json
add python-27-rhel7-var.json file ,help to merge,thx
=> add scl image python27 file

templates/perl516psql94/dancer-perl-psql94.json
=> Added testfile for perl psql.

build/ruby22rhel7-template-docker-blankrepo.json
Could you please help to merge, thx!
=> create test file for blank source repo

build/ruby22rhel7-template-docker-invalidrepo.json
Could you please help to merge, thanks!
=> add testfile for invalid source repo

build/ruby20rhel7-invalidcontext-docker.json
Could you please review and merge, thanks!
=> add testfile about invalid context folder

routing/tc477695/hello.json, routing/tc477695/new_route.json, templates/tc470452/ruby20rhel7-template-sti.json
Please help me review and merge it ,thanks!
=> add json file for tc477695

persistent-volumes/nfs/pv-invalid-path.json
add json file with non-exist nfs path in PV
=> add json file for case 510432

build/stibuild-configchange.json
Could you please help to merge? thanks!
=> add test file for case 497874

build/ruby20centos7-env-sti.json
Updated repository.
Updated image to use centos repo.
Removed explicit namespace.
Removed extraneous comma.
=> Added testfile for tc499490

image/language-image-templates/php55-upload-demo.json, image/language-image-templates/php56-upload-demo.json
Could you please help to merge the two test files? thanks!
=> create testfile for bug 1249794

templates/tc482217/hello-pod.json
=> Added files for tc482217.

persistent-volumes/nfs/auto-nfs-recycle-rwo.json
The PV json file for case 508049
=> json file for case 508049 automation

networking/external_service_to_external_pod.json, templates/tc509059/sa.yaml, templates/tc509059/service.json, templates/tc509065/service.json
1. update external_service_to_external_pod.json due to below errors:
oc expose service selector-less-service --config=/root/workdir/dhcp-128-8-root/origin_chunchen.kubeconfig -n 57rg0
error: couldn't find selectors via --selector flag or introspection: the service has no pod selector set
see 'oc expose -h' for help.
2. others json files are added for automating TC 509059, 509065
=> add and update template json files

pods/pod-with-v1beta3.json
=> Add pod-with-v1beta3.json to test version converted case #510225

templates/tc479022/application-template-custombuild.json
The only additions were line 139 and 140 to add the proxy env.
=> Added template file for TCMS case #479022.

templates/tc515805/tc515805.json
Added json file for TCMS case #515805.
=> Added json file for TCMS case #515805.

image-streams/tc510524.json, image-streams/tc510529.json
@bmeng @jhou1 Please help me review,thanks!
=> add json file for tc510524 tc510529

downwardapi/tc482265/downward-example.yaml
Updated pod image.
Updated image.
Updated image.
Updated image.
Updated image.
=> Added yaml file for TCMS case #483203.

templates/tc512262/Dockerfile
Added Dockerfile for tc512262.
=> Added Dockerfile for tc512262.

cases/510690/pod.json
The json file used to create pods in test case 510690
=> pod json file for case 510690

deployment/tc510612/hook-inheritance-secret-volume.json, pods/pod_with_special_fsGroup.json, pods/pod_with_special_supplementalGroups.json
=> add json for case 510612

templates/tc511597/job.yaml
Added template file for TCMS case #511597.
=> Added template file for TCMS case #511597.

templates/tc511597/job.yaml
Updated job tag version for tc511597
=> Updated job tag version for tc511597

authorization/policy/getlistwatch_projNamespace.json
=> add clusterrole for case 470662

daemon/daemonset_node_selector.yaml, daemon/daemonset_sample.yaml
update daemonset apiVersion to "extensions/v1beta1"
=> Update daemonset apiVersion

routing/unsecure/service-2ports.json
=> add service and route for tc511913

image/language-image-templates/template_onbuild.json
Ensure docker pull dockerhub image successfully.
=> Ensure docker pull dockerhub image successfully.

image-streams/image-source-with-fake-api-group.yaml
as title, added one template file contains fake api group
=> add test file for tc518663

image-streams/image-source.yaml
as title, add test files for tc518658
=> add test file for tc518658

image/language-image-templates/cakephp-mysql.json, image/language-image-templates/cakephp.json
Could you please review and merge, thanks!
=> add quickstart template for php-55 image

deployment/deployments_nobc_cpulimit.json
@wsun1 this deployment template is for create dc and is with mem and cpu
=> add dc with is,mem,cpu

build/tc479296/application-template-custombuild.json
Add a new template for case 479296. Please check it. Thanks!
=> add a new template for case 479296

templates/tc509045/40.json
Added testfile for tc 509045 evaluation.
=> Added testfile for tc 509045 evaluation.

templates/tc467937/pod467937.yaml
=> Added template for TC 467937.

templates/tc470327/python-34-rhel7-stibuild.json
=> Added testfile for TC 470327.

persistent-volumes/gce/claim-rwo-dynamic.json
The json file used to test dynamic provison for GCE
=> add gce dynamic provison test file

image/language-image-templates/python-27-rhel7-stibuild.json, image/language-image-templates/python-27-rhel7-var.json, image/language-image-templates/python-33-rhel7-var.json, image/language-image-templates/python-34-rhel7-stibuild.json
update python template to fit  online auto test
=> update python template

deployment/rc-with-two-containers.yaml
Checked the file works.
$ oc create -f rc-with-two-containers.yaml
replicationcontroller "rctest" created
$ oc get pod
NAME              READY     STATUS             RESTARTS   AGE
rctest-6glr6      2/2       Running            0          5m
=> Add rc-with-two-containers.yaml

templates/tc517667/ruby22rhel7-template-sti.json
=> Added testfile for TC 517667.

persistent-volumes/gce/pod-NoDiskConflict-1.json, persistent-volumes/gce/pod-NoDiskConflict-2.json, storage/nfs/nfs-server.yaml
Test files for test case 522125/522126
=> add sample file for NoDiskConflict

templates/tc517666/ruby22rhel7-template-sti.json
=> Added json file for tc517666.

configmap/configmap.yaml, configmap/pod-configmap-command.yaml, configmap/pod-configmap-env.yaml, configmap/pod-configmap-volume1.yaml, configmap/pod-configmap-volume2.yaml, daemon/daemonset-nodeselector.yaml, daemon/daemonset.yaml, job/job-manualselector.yaml, job/job-restartpolicy.yaml, job/job-runonce.yaml, job/job-secret-env.yaml, job/job.yaml, secrets/secret-env-pod.yaml, secrets/secret-pod.yaml, secrets/secret.yaml
Add job and configmap, update daemon and secret
=> Add job and configmap, update daemon and secret

deployment/tc519261/test.json, deployment/tc519261/testsecret1.json, deployment/tc519261/testsecret2.json
=> addfile_519261

pods/pod-with-probe.yaml
refer to case 519503
@wsun1 plz help to review
=> add pod-with-probe.yaml

persistent-volumes/nfs/pv-template.json, persistent-volumes/nfs/pvc-template.json
PVC should bound the PV with most appropriate access mode and size
=> add template files for test case 522127

online/dynamic_persistent_volumes/pod-mongodb.yaml, online/dynamic_persistent_volumes/pvc-less.yaml, online/dynamic_persistent_volumes/pvc-mongodb.yaml, online/dynamic_persistent_volumes/pvc-over-replace.yaml, online/dynamic_persistent_volumes/pvc-over.yaml, online/dynamic_persistent_volumes/pvc_gce.yaml
Test files of online dynamic persistent volumes
=> Test files of online dynamic persistent volumes

build/tc470322/test-template.json, build/tc470322/test-template_2.json
add two file for auto case 470322, Please review them. thanks!
=> add_case_470322

build/Dockerfile_onbuild_nosh, build/Dockerfile_onbuild_notar
add dockerfile to verify bug https://bugzilla.redhat.com/show_bug.cgi?id=1330735
=> add dockerfile 

image-streams/tc516702.json
Image stream for case: https://tcms.engineering.redhat.com/case/516702/?from_plan=14587
@wsun1 pls help to merge, thanks!
=> imagefile for case516702

templates/tc507415/application-template-custombuild.json
=> Added template for tc507415.

persistent-volumes/ebs/tc519501/dynamicpv-created.sh
@jhou1  please help review and merge
=> script for tc519501

services/multi-portsvc.json
Add a test service file which contains multiple ports
=> add test service file with multi port

job/job-secret-env.yaml, job/job.yaml, job/job_with_0_activeDeadlineSeconds.yaml, job/job_with_float_activeDeadlineSeconds.yaml, job/job_with_lessthan_runtime_activeDeadlineSeconds.yaml, job/job_with_long_activeDeadlineSeconds.yaml, job/job_with_negative_activeDeadlineSeconds.yaml, job/job_with_string_activeDeadlineSeconds.yaml
If we manually set selector for job, need set "manualSelector: true" too.
=> Update job with manualSelector

image/db-templates/postgresql-92-rhel7-env-test.json, image/db-templates/postgresql-94-rhel7-env-test.json
already test online ,works, please help to merge
=> update emptydir instead of docker volume in template

configmap/configmap-example.yaml
@mdshuai  please help to review.
=> Add a yaml file for configmap case 520895

quota/quota_template.yaml, quota/tc509087/mysecret.json, quota/tc519922/pod-request-limit-valid-4.yaml
@qwang1  Could you help to review？ Thx.
=> Add test files for tc509087 tc509088 tc509089 and tc519922

routing/reencrypt/no_cert.json
=> update service name

build/tc525734/Nonesrc-docker.json
=> addfile_tc525734

build/tc525736/Nonesrc-sti.json
=> addfile_tc525736

cases/510532/pod.json
Remove securityContext part from container.
=> minor update for automation

cases/510690/pod.json
=> remove securityContext from container part

templates/tc519487/bc1.json, templates/tc519487/bc2.json, templates/tc519487/bc3.json, templates/tc519487/bc4.json, templates/tc519487/bc5.json, templates/tc519487/bc6.json
Added testfiles for TCMS case #519487. The 'patch' command previously used did not behave as expected.
=> Added testfiles for TCMS case #519487.

build/tc525736/nosrc-setup.json
add the file in testcase to public repo.  please reivew.
=> addcasefile525736

build/tc476354/pushimage.json
=> modify tc476354 template

build/tc527410/longname-build-withlabel.json, build/tc527410/longname-build.json
add longname build file for case527410.
=> addfile_527410

persistent-volumes/ebs/tc521600/create-50-pv.sh
@jhou1  please help merge this pr
=> script for tc521600

logging_metrics/metrics_pv.json
in order for automate test case 518907, Scenario: Deploy metrics stack with persistent storage
=> PV template for metrics testing

templates/test-api.yaml
Add test file for 518662, includes different apis
=> add test file for 518662

deployment/deployments_nobc_cpulimit.json, image-streams/is_without_tags.json, persistent-volumes/ebs/pv-rox.yaml, persistent-volumes/ebs/pv-rwo.yaml, persistent-volumes/ebs/pv-rwx.yaml, templates/tc467937/pod467937.yaml, templates/tc497680/nodejs-template-stibuild.json
Some test files are still using v1beta1 or v1beta3, update it to latest.
=> update api version from v1beta to v1

limits/518638/limits.yaml
add test files for tc518638 and tc518639
=> add test files for tc518638 and tc518639

persistent-volumes/misc/pvc-ERB.json
Test file currently for tc519501, but it can be used for other cases, too.
=> add ERB pvc json file

image/db-templates/postgresql-94-ephemeral-template.json, image/db-templates/postgresql-95-ephemeral-template.json
=> add psql95 template

pods/pod-invalid.yaml, pods/tc510724/pod-supplementalGroups-invalid.yaml, pods/tc510724/pod-supplementalGroups-multi-cotainers.yaml, pods/tc510724/pod-supplementalGroups.yaml
@mdshuai  Please help to review and merge. Thanks.
=> Add test files for TC510724 and TC515449

limits/limits.yaml
@wsun1 Could you please help to review and merge? Thanks!
=> Add a generate limit template

templates/tc517666/ruby22rhel7-template-sti.json, templates/tc517667/ruby22rhel7-template-sti.json, templates/tc517668/ruby22rhel7-template-docker.json
In online env, using jenkins image as source image, will failed due to can't create source image container, need add volume, so change to use python image.
=> Modify testfiles tc517666,tc517667,tc517668

authorization/scc/gitrepo-for-scc-migration.json, groups/ad/sync-config.yaml, groups/augmented-ad/sync-config.yaml, groups/rfc2307/sync-config.yaml
1> Update ldap config group name mapping to make group name will not affect each other for different cases
2> Add a gitrepo volume pod for scc migration case.
=> Update ldap config group name mapping 

routing/customrouter/haproxy-config-custom.template
just update the edge map file name from 'os_edge_http_be.map' to 'os_edge_custom.map'
=> [networking]add custom haproxy config

cases/509014/frontend-controller.yaml, cases/509014/redis-master-controller.yaml
=> add redis-master-controller.yaml and frontend-controller.yaml

groups/rfc2307/add-user-to-group.ldif, groups/rfc2307/sync-config-user-defined.yaml
@wsun help me review and merge, thx
=> Add and update data for tc509128

cli/tc519471/image-stream-tag-update.json, cli/tc519471/image-stream-tag.json
Changed the json files to json erb files so they reflect the correct product docker repo.
=> TC 519471. added product_docker_repo to the json. creating an erb template.

persistent-volumes/ebs/labelmatch/pv1.json, persistent-volumes/ebs/labelmatch/pv3.json, persistent-volumes/ebs/labelmatch/pv4.json, persistent-volumes/ebs/labelmatch/pv5.json, persistent-volumes/ebs/labelmatch/pv6.json, persistent-volumes/ebs/labelmatch/pv8.json, persistent-volumes/ebs/labelmatch/pvc5.json
Add pv labels usedFor=xxx to auto test case
=> Update labelselector test file

templates/tc476356/application-template-dockerbuild.json, templates/tc476357/application-template-stibuild.json
=> update image name for pushing

templates/application-template-stibuild.json
Add a template with messages defined for case 532281
=> add a test template with messages

routing/tc/tc477695/hello.json
Add path field for route which could be changed
=> update test files for 477695

templates/tc518660/application-template-dockerbuild.json
Add test template file for 518660
=> add test files for 518660

templates/tc518660/application-template-stibuild.json
update test files for tc518660
=> update test files for tc518660

quota/tc532979/nodeport-svc1.json, quota/tc532979/nodeport-svc2.json, quota/tc532979/nodeport-svc3.json, quota/tc532979/quota-service.yaml, quota/tc532980/multi-nodeports-svc.json
@mdshuai Could you help to review and merge? Thanks.
=> add test files for TCs 532979 532980 532981

templates/tc515804/application-template-stibuild.json
Add a template file contains "v1beta3"
=> add test file for tc515804

persistent-volumes/nfs/labelmatch/pv1.json, persistent-volumes/nfs/labelmatch/pv2.json, persistent-volumes/nfs/labelmatch/pv3.json, persistent-volumes/nfs/labelmatch/pv4.json, persistent-volumes/nfs/labelmatch/pv5.json, persistent-volumes/nfs/labelmatch/pv6.json, persistent-volumes/nfs/labelmatch/pv7.json, persistent-volumes/nfs/labelmatch/pv8.json, persistent-volumes/nfs/labelmatch/pvc1.json, persistent-volumes/nfs/labelmatch/pvc2.json, persistent-volumes/nfs/labelmatch/pvc3.json, persistent-volumes/nfs/labelmatch/pvc4.json, persistent-volumes/nfs/labelmatch/pvc5.json, persistent-volumes/nfs/labelmatch/pvc6.json, persistent-volumes/nfs/labelmatch/pvc7.json, persistent-volumes/nfs/labelmatch/pvc8.json
Update these files due to using nfs volume to auto test case about label selector feature
=> Update files for auto labelselector feature

configmap/pod-configmap-redis.yaml
@mdshuai Please help to review and merge. Thanks.
=> add test file for TC 520909

pods/initContainers/init-containers-always.yaml, pods/initContainers/init-containers-deadline.yaml, pods/initContainers/init-containers-fail.yaml, pods/initContainers/init-containers-never.yaml, pods/initContainers/init-containers-onfailure.yaml, pods/initContainers/init-containers-privilege.yaml, pods/initContainers/init-containers-quota-1.yaml, pods/initContainers/init-containers-quota-2.yaml, pods/initContainers/init-containers-readiness.yaml, pods/initContainers/init-containers-sleep.yaml, pods/initContainers/init-containers-success.yaml, pods/initContainers/initContainer.yaml, pods/initContainers/quota.yaml, pods/initContainers/volume-init-containers.yaml
Add test files for initContainers
=> Add initContainers test files

routing/list_for_pods.json
add a rc  pod service for idle testing
=> add rc pod servce

configmap/configmap-multi-volume.yaml, configmap/configmap-path.yaml, configmap/pod-configmap-path.yaml, configmap/pod-configmap-same.yaml, configmap/pod-multi-volume.yaml, secrets/pod-multi-volume.yaml
These yaml files are for new user story's test cases related to configmap and secrets
=> Prepared configmap and pod yaml for new test cases

hpa/dc-hello-openshift.yaml, hpa/rc-hello-openshift.yaml
=> add test files for hpa TCs

rc/idle-rc-1.yaml, rc/idle-rc-2.yaml
=> Add rc yaml files for idle TCs

pods/tc532324/pod_nodeSelector_infra.yaml
Added template file for auto [case](https://tcms.engineering.redhat.com/case/532324/?from_plan=14587)
=> test file for tc 532324

deployment/hello-deployment-1.yaml, deployment/hello-deployment-2.yaml
=> add deployment yaml files for Proportionally scale

deployment/deployment-with-service.yaml
add test file "deployment-with-service" for 533674 idle features
=> add test file for 533674

quota/pod-completed.yaml
@mdshuai Please help to review. Thx.
=> add test files for quota testing

quota/pod-besteffort-terminating.yaml
=> add test file for quota testing

build/tc528951/bc_configchange.yaml, build/tc528954/bc_imagechange.yaml, build/tc528955/bc_no_trigger.yaml
Used in https://github.com/openshift/cucushift/pull/3927 and passed in https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/5391/console
@yapei PTAL, thank you!
=> For auto of 528951 528954 528955

authorization/scc/pod_seccomp_1.yaml, authorization/scc/pod_seccomp_2.yaml
@mdshuai Add test files for seccomp testing. Please help to merge.
=> add test files for seccomp

image/language-image-templates/tc532767/template.json
@akostadinov can you merge please?
=> testfile for tc 532767

persistent-volumes/misc/storageClass.yaml
The sample file for storageClass used for automation.
=> Add storageClass yaml file

templates/tc525737/application-template-custombuild.json, templates/tc525738/application-template-stibuild.json
Add test file for tc525737 and tc525738
=> add test file for tc525737 and tc525738

quota/pod-burstable.yaml, quota/pod-guaranteed.yaml
@mdshuai please review and merge test files. thanks
=> add test files for TC534961, TC534962

persistent-volumes/cinder/dynamic-provisioning/storageclass.yaml, persistent-volumes/gluster/dynamic-provisioning/storageclass.yaml, persistent-volumes/misc/storageClass.yaml
=> Update StorageClass API version

templates/tc481680/application-template-with-resources.json
Pls help merge, thanks! @yapei
=> add test file for case 481680

persistent-volumes/misc/pvc-without-annotations.json
Copied from pvc.json and removed the annotations field.
=> Add pvc template without annotations

deployment/tc528860/dc-hello-hpa.yaml
add a test dc file to create HPA
=> add test file for 528860

daemon/daemonset-negtive-never.yaml, daemon/daemonset-negtive-onfailure.yaml
@mdshuai  Please help to merge. Thx.
=> add two negative test files for daemonset

downwardapi/tc509097/pod-downwardapi-env.yaml, quota/pod-notbesteffort.yaml, secrets/mapping-secret-volume-pod.yaml, secrets/tc483168/second-secret-pod.yaml, secrets/tc483169/secret-pod-1.yaml
@mdshuai please review and merge. Thanks.
=> change image to meet online constraint

downwardapi/tc509097/pod-downwardapi-env.yaml, quota/pod-notbesteffort.yaml, secrets/mapping-secret-volume-pod.yaml, secrets/tc483168/second-secret-pod.yaml, secrets/tc483169/secret-pod-1.yaml
@mdshuai  please review and merge if it is fine.
=> replace broken image

persistent-volumes/gce/storageClass.yaml
Currently misc/storageClass.yaml is specific for GCE, this PR fixed that.
=> Update misc/storageClass.yaml; Add gce/storageClass.yaml

hpa/dc-hello-openshift.yaml, hpa/rc-hello-openshift.yaml, rc/idle-rc-1.yaml, rc/idle-rc-2.yaml, routing/passthrough/stickysession/service_stickysession.json
Update 'tcp' to 'TCP' avoid some error when create resource
```
[root@ip-172-18-7-27 dma]# oc create -f svc.yaml -n dma
The Service "tls-service" is invalid: spec.ports[0].protocol: Unsupported value: "tcp": supported values: TCP, UDP
```
=> Update tcp to TCP

pods/pod-pull-by-digests.yaml, pods/pod-pull-by-tag.yaml
@mdshuai Please help to review and merge. Thx.
=> add test files for imageID testing

persistent-volumes/misc/storageClass-emptyName.yaml, persistent-volumes/misc/storageClass-invalidAPI.yaml, persistent-volumes/misc/storageClass-invalidName.yaml
Add 3 files.
storageClass-invalidAPI.yaml
storageClass-emptyName.yaml
storageClass-invalidName.yaml
The name itself should be able to describe its use case.
=> Add test template file for storageClass negative test

deployment/tc518650/test.json
| Test Case | `dev_preview_stg` | `ose` |
| :-: | :-: | :-: |
| [518650](https://tcms.engineering.redhat.com/case/518650/) | [build](https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/7462/console) | [build](https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/7463/console) |
@pruan-rht, @zhouying7780 review changes, please!
=> Fix 518650 test file for Online

pods/tc533910/readiness-probe-exec.yaml
add tc533910/readiness-probe-exec.yaml for automation
=> add tc533910/readiness-probe-exec.yaml

secrets/tc483168/first-secret-pod.yaml, secrets/tc483169/secret-pod-2.yaml
Please, don't merge until changes acked by feature team in https://github.com/openshift/cucushift/pull/4177
=> Fix 483168 483169 testfile for Online

persistent-volumes/azure/azcaro-pod.yaml, persistent-volumes/azure/azntfspod.yaml, persistent-volumes/azure/azpod.yaml, persistent-volumes/azure/azpv.yaml, persistent-volumes/azure/azpvc.yaml, persistent-volumes/azure/azpvcpod.yaml, persistent-volumes/azure/azpvdelete.yaml, persistent-volumes/azure/azrarw-pod.yaml, persistent-volumes/azure/azrwro-pod.yaml, persistent-volumes/azure/azxfspod.yaml
=> Add all azure related test files

pods/tc538208/pdb_more_than_full_percentage.yaml, pods/tc538208/pdb_negative_absolute_number.yaml, pods/tc538208/pdb_negative_percentage.yaml, pods/tc538208/pdb_non_absolute_number.yaml, pods/tc538208/pdb_non_number_percentage.yaml, pods/tc538208/pdb_positive_absolute_number.yaml, pods/tc538208/pdb_reasonable_percentage.yaml, pods/tc538208/pdb_zero_number.yaml, pods/tc538208/pdb_zero_percentage.yaml
@wsun1 @zhouying7780 please help review, thanks.
=> auto case 538208

image/db-templates/mysql55-ephemeral-template.json, image/db-templates/mysql55-persistent-template.json, image/db-templates/postgresql-92-ephemeral-template.json, image/db-templates/postgresql-94-ephemeral-template.json, image/db-templates/postgresql-95-ephemeral-template.json
@wanghaoran1988 pls review
[for ose3.3](https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/8458/console)
[for ose3.4](https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/8475/console)
=> remove-container-image-for-db-template

deployment/dc-with-two-containers.yaml
Updated image to not use personal account.
=> Updated image to not use personal account.

admin/tc521728_add_user_to_ldap.ldif
@wsun1 please help merge this file, thanks.
=> auto case 521728

pods/pv-recycler-invalid.json
Used in test case 540165 to simplify the first step in setup.
=> Add invalid recycler template for negative testing

deployment/tc536593/deployment-with-two-containers.yaml
=> add test file for tc536593

pods/permission-data/configmap-keys-permission-pod.yaml, pods/permission-data/configmap-permission-pod.yaml, pods/permission-data/dapi-keys-permission-pod.yaml, pods/permission-data/dapi-permission-pod.yaml, pods/permission-data/secret-keys-permission-pod.yaml, pods/permission-data/secret-mix-permission-pod.yaml, pods/permission-data/secret-permission-pod.yaml
@mdshuai Could you help to merge? Thx.
=> add test files for permission test

admin/tc509116/tc509116_identity.json, admin/tc509116/tc509116_user.json, admin/tc509116/tc509116_useridentitymapping.json
@wsun1 Please help merge these files, thanks.
=> auto case 509116

authorization/scc/tc538262/PodSecurityPolicySubjectReview_privileged_false.json, authorization/scc/tc538262/PodSecurityPolicySubjectReview_privileged_true.json, authorization/scc/tc538263/PodSecurityPolicySubjectReview.json, authorization/scc/tc538264/PodSecurityPolicyReview.json
@wsun1 please help merge these files auto for case 538262/538263/538264, thanks.
=> auto case 538262 538263 538264

templates/tc544375/ruby22rhel7-template-docker.json.failtopush
Change "output" to "DockerImage" and push image to private docker without a secret
=> add test file for tc544375

templates/tc532330/jenkins-slave-template.json
@wanghaoran1988 please help review
=> add jenkins slave template for tc532330,536421

image-streams/imagesignature.yaml
@wsun1  please help merge , thanks .
=> update imagesignature.yaml file

secrets/credential/.gitconfig
=> move the pub gitconfig to secrets dir

quota/tc536555/pod-besteffort.yaml, quota/tc536555/pod-notbesteffort.yaml, quota/tc536555/pod-notterminating.yaml, quota/tc536555/pod-terminating.yaml, quota/tc536555/quota-besteffort.yaml, quota/tc536555/quota-notbesteffort.yaml, quota/tc536555/quota-notterminating.yaml, quota/tc536555/quota-terminating.yaml
@yapei @wsun1  pls help to reivew and merge
=> add testfile for case 536555

admin/Eviction.json, admin/PodDisruptionBudget.yaml
@wsun1 could you please help to merge?
=> add file for PDB

petset/hello-petset.yaml
@yapei pls help to review and merge, thanks!
=> add petset test file

cli/tc519882/squid.conf
@yapei please help merge for auto PR 4453, thanks!
=> add authenticated squid.conf

replicaSet/tc536594/replicaset-with-two-containers.yaml
Add replicasest with two containers test file for tc536594
=> add test file for tc536594

persistent-volumes/misc/pvc.json, persistent-volumes/nfs/claim-rwo.json
Fix
http://ci-qe-openshift.nay.redhat.com/userContent/cucushift/v3/2017/01/16/06:48:51/PVC_creation_negative_testing/console.html
http://ci-qe-openshift.nay.redhat.com/userContent/cucushift/v3/2017/01/16/06:47:09/Using_both_alpha_and_beta_annotation_in_PVC/console.html
=> Change pvc size to match the limit on Online

job/scheduledjob_with_startingDeadlineSeconds.yaml
@wsun1 , I added "scheduledjob_with_startingDeadlineSeconds.yaml." to v3-testfiles/job for automation, pls help to review and merge it, thanks in advance.
=> add "scheduledjob_with_startingDeadlineSeconds.yaml." to v3-testfiles/job for automation

secrets/tc483170/secret-nginx-2.yaml, secrets/tc483170/secret-pod-nginx-2.yaml
=> add test files for TC 483170

secrets/tc483170/secret-pod-nginx-2.yaml
Fix yaml issue. @mdshuai Please to merge. Thanks.
=> fix secret-pod-nginx-2.yaml

pods/ocp12897/pdb_more_than_full_percentage.yaml, pods/ocp12897/pdb_negative_absolute_number.yaml, pods/ocp12897/pdb_negative_percentage.yaml, pods/ocp12897/pdb_non_absolute_number.yaml, pods/ocp12897/pdb_non_number_percentage.yaml, pods/ocp12897/pdb_positive_absolute_number.yaml, pods/ocp12897/pdb_reasonable_percentage.yaml, pods/ocp12897/pdb_zero_number.yaml, pods/ocp12897/pdb_zero_percentage.yaml
@wsun1 would you please help merge these files for auto case OCP-12897, thanks
=> auto case 12897

deployment/deployment-perme-failed-1.yaml, deployment/deployment-perme-failed-2.yaml, deployment/deployment-perme-failed-3.yaml
@mdshuai Please help to merge. Thanks.
=> add deployment test files

pods/sysctls/pod-sysctl-safe-invalid1.yaml, pods/sysctls/pod-sysctl-safe-invalid2.yaml, pods/sysctls/pod-sysctl-safe-invalid3.yaml
@mdshuai Please help to merge. Thanks
=> add test files for sysctl-safe

pods/busybox-pod.yaml, services/ExternalSvc-cannot-resolve.yaml, services/ExternalSvc-with-IP.yaml, services/ExternalSvc-with-port.yaml, services/ExternalSvc.yaml
@mdshuai Please help to review and merge. Thx
=> add test files for external svc

services/ExternalSvc-with-IP.yaml, services/ExternalSvc-with-port.yaml
=> Update external svc test files

templates/OCP-12163/pipeline_scale_deployment.groovy
@akostadinov could you give me the permission so I can merge by myself ?
=> add goroovy file for OCP-12163

templates/OCP-12163/pipeline_scale_deployment.groovy, templates/OCP-12219/tag_image.groovy, templates/OCP-12267/trigger_build.groovy, templates/OCP-12267/trigger_build_failed.groovy, templates/OCP-12267/trigger_build_verbose.groovy, templates/OCP-12297/trigger_deployment.groovy, templates/OCP-12297/trigger_deployment_failed.groovy, templates/OCP-12297/trigger_deployment_verbose.groovy
@cjryan ptal 
@akostadinov could you add me a permission so I can merge by myself ?
=> add goroovy file

build/tc515317_536388/jenkins-with-plugins.json, templates/OCP-12163/pipeline_scale_deployment.groovy, templates/OCP-12219/tag_image.groovy, templates/OCP-12267/trigger_build.groovy, templates/OCP-12267/trigger_build_failed.groovy, templates/OCP-12267/trigger_build_verbose.groovy, templates/OCP-12297/trigger_deployment.groovy, templates/OCP-12297/trigger_deployment_failed.groovy, templates/OCP-12297/trigger_deployment_verbose.groovy
address problem: https://github.com/openshift/cucushift/pull/4466#discussion-diff-100161444R1467
@cjryan, @akostadinov  ptal
=> update  template: enable oath env

templates/OCP-12325/pipeline_verify_build.groovy, templates/OCP-12347/pipeline_verify_deployment.groovy, templates/OCP-12371/pipeline_verify_service.groovy, templates/OCP-12371/pipeline_verify_service_failed.groovy
follow up: https://github.com/openshift/cucushift/pull/4562
@wzheng1 @dongboyan77 @cjryan PTAL, thanks
=> add groovy file for jenkins pipeline scripts

admission/podnodeselector/invalid-namespace.yaml, admission/podnodeselector/ns1.yaml, admission/podnodeselector/pod-nodeSelector1.yaml, admission/podnodeselector/pod-nodeSelector2.yaml, admission/podnodeselector/pod-nodeSelector3.yaml, admission/podnodeselector/pod-nodeSelector4.yaml, admission/podnodeselector/valid-namesapce.yaml
@mdshuai Please help to confirm and merge. Thx.
=> add test files for NodeSelector

authorization/scc/scc_drop_all_cap.yaml, authorization/scc/scc_with_all_cap.yaml
=> add file for scc with capabilities

secrets/tc483170/secret-nginx-2.yaml
@mdshuai help review and merge. thanks
=> update file secrets/tc483170/secret-nginx-2.yaml

scheduler/opaque_integer_resources/pod_invailid5.yaml, scheduler/opaque_integer_resources/pod_invailid_limits3.yaml, scheduler/opaque_integer_resources/pod_invailid_limits4.yaml, scheduler/opaque_integer_resources/pod_invailid_requests1.yaml, scheduler/opaque_integer_resources/pod_invailid_requests2.yaml, secrets/tc483170/secret-nginx-2.yaml
@mdshuai please review and merge. Thanks.
=> Add yaml files for opaque integer resources automation tests 

persistent-volumes/gce/pv-with-failure-domain.json
Used to automate test case OCP-10219
=> Add pv test file with failure domain

templates/tc528448/sample-app-database-dc-resources-large-invalid.json
change default timeoutSeconds from 10mins to 60s, so automation no need wait long time.
logs: http://pastebin.test.redhat.com/457914
@qwang1 help review.
=> add timeoutSeconds for tc528448

authorization/scc/scc_with_confilict_capabilities.yaml, cli/tc519471/image-stream-tag-update.json, cli/tc519471/image-stream-tag.json
@wanghaoran1988  @wsun1 Could you please review and help merge ?
=> update repo for image and add file for scc with confilict cap

statefulset/hello-statefulset.yaml, statefulset/stable-storage.yaml, statefulset/update-statefulset.yaml
Add test-files for statefulset
=> add test-files for statefulset

image/language-image-templates/OCP-13135/template.json, image/language-image-templates/OCP-13136/template.json, image/language-image-templates/OCP-13141/template.json, image/language-image-templates/tc521461/template.json, image/language-image-templates/tc521462/template.json, templates/OCP-12297/trigger_deployment_failed.groovy
ref: https://github.com/openshift/cucushift/pull/4614
@wzheng1 @xiuwang @cjryan PTAL, also related to :https://github.com/openshift/cucushift/pull/4614
=> fix cpu memory limits problem

networking/multicast-rc.json
@bmeng please help review, thanks
=> add rc file for multicast test pod

routing/upgrade/pod1.json, routing/upgrade/pod2.json
=> Add testfiles for testing sticky session upgrade

secrets/OCP-11410/mysecret-1.yaml, secrets/OCP-11410/mysecret-2.yaml
=> add test files for OCP-11410

scheduler/pod_with_nodename.json
@wmengRH @mdshuai Please review and merge.
cc @lihongan
=> change the host to nodeName according to the latest behaviour

persistent-volumes/azure/azfile-pod.yaml, persistent-volumes/azure/azpv-ano.yaml, persistent-volumes/azure/azpvc-esc.yaml, persistent-volumes/azure/azpvc-nsc.yaml, persistent-volumes/azure/azpvc-sc.yaml, persistent-volumes/azure/azpvc-scw.yaml, persistent-volumes/azure/azpvc-wsc.yaml, persistent-volumes/azure/azsc-ACONLY.yaml, persistent-volumes/azure/azsc-CENTRAL.yaml, persistent-volumes/azure/azsc-COMBSL.yaml, persistent-volumes/azure/azsc-GRS.yaml, persistent-volumes/azure/azsc-IGNOR.yaml, persistent-volumes/azure/azsc-LCONLY.yaml, persistent-volumes/azure/azsc-LRS.yaml, persistent-volumes/azure/azsc-NOPAR.yaml, persistent-volumes/azure/azsc-PLRS.yaml, persistent-volumes/azure/azsc-RAGRS.yaml, persistent-volumes/azure/azsc-WEST.yaml, persistent-volumes/azure/azsc-WRAGRS.yaml, persistent-volumes/azure/azsc-ZRS.yaml, persistent-volumes/azure/azsc-invalid.yaml, persistent-volumes/azure/azsc-noext.yaml, persistent-volumes/azure/azscw-WLRS.yaml
=> Added azure dynamic provision test files

templates/OCP-12856/push-generic-build-args.json
=> add push-generic template for ocp-12856

build/test-gitserver.yaml, templates/OCP-11025/test-build.json
Add testfiles for ocp-11025
And update test-gitserver.yaml
=> Add testfiles for ocp-10942 and ocp-11025

authorization/policy/OCP-13479/rolebindingrestriction.yaml
@wanghaoran1988 please help merge file for OCP-13479, thanks.
=> add file for OCP-13479

cli/OCP-11680/guestbook.json, cli/OCP-11680/template_required_params.yaml
https://github.com/openshift/cucushift/pull/4784
=> case OCP-11680

persistent-volumes/nfs/nfs-provisioner/nfsdyn-pod.yaml, persistent-volumes/nfs/nfs-provisioner/nfsdyn-pvc.yaml, persistent-volumes/nfs/nfs-provisioner/nfsdyn-sc.yaml, persistent-volumes/nfs/pv-mount-option.yaml
=> Add test files for nfs-provisioner

templates/OCP-13848/project-request.json
@wzheng1 please help merge, thanks
=> add rolebinding restriction template for OCP-13848

deployment/tc536593/deployment-with-two-containers.yaml
@xxing Please review and merge, thanks
=> Update tc536593/deployment-with-two-containers.yaml for online limit

deployment/tc536593/deployment-with-two-containers.yaml, replicaSet/tc536594/replicaset-with-two-containers.yaml
@xxing Please review and merge, thanks!
=> Update resources replicas for online

persistent-volumes/azure/security/azure-privileged-test.yml, persistent-volumes/azure/security/azure-selinux-fsgroup-test.yml
=> Add security test files for Azure disk

deployment/deployment-perme-failed-1.yaml, deployment/deployment-perme-failed-2.yaml, deployment/deployment-perme-failed-3.yaml, quota/application-template-with-resources.json, replicaSet/tc533162/rs_endpoints.yaml
@akostadinov Could you please help review ? thanks !
=> update for online quota

online/dynamic_persistent_volumes/pvc-annotation-alpha.json, online/dynamic_persistent_volumes/pvc-annotation-blank.json, online/dynamic_persistent_volumes/pvc-annotation-default.json, online/dynamic_persistent_volumes/pvc-annotation-ebs.json, online/dynamic_persistent_volumes/pvc-annotation-notexist.json, online/dynamic_persistent_volumes/pvc-equal.yaml
Hi admin,
These files are used for autoscript for online storage. Please help check and merge them. Thanks.
@yufchang @bingli7  @ychww @zhezli please help review the files
=> Prepare pvc files for Online Storage testing

persistent-volumes/misc/storageClass-without-annotations.yaml
@jhou  Could you help review ? Thanks.
=> Add storageclass template without annotations

online/dynamic_persistent_volumes/pvc-annotation-alpha.json, online/dynamic_persistent_volumes/pvc-annotation-blank.json, online/dynamic_persistent_volumes/pvc-annotation-default.json, online/dynamic_persistent_volumes/pvc-annotation-ebs.json, online/dynamic_persistent_volumes/pvc-annotation-notexist.json
@jhou1  please help merge the updating. Thanks
=> update the pvc name same as the filename

deployment/deployment1.json, deployment/updatev1.json
@wanghaoran1988 Could you please help review and merge ? thanks .
=> add limit for dc json file

templates/tc517670/dc.json
change pod replicas to 1, due to limited resource on OSO free
@wzheng1 please review, thx
=> update template for ocp-11943

configmap/pod-configmap-security.yaml, downwardapi/pod-dapi-security.yaml, persistent-volumes/azure/dc.yaml
=> Add security testing files for configmap and downwardapi

persistent-volumes/misc/pvc-with-storageClassName.json
New attribute "storageClassName" introduced in 3.6
=> Add test file pvc-with-storageClassName.json

routing/caddy-docker-2.json, routing/caddy-docker.json
update memory to 300m since it has forbidden for online-int
=> update memroy to 300m for online-int testing

persistent-volumes/misc/storageClass-with-beta-annotations.yaml, persistent-volumes/misc/storageClass-with-stable-annotations.yaml
Add different versions since they interfere with each other.
=> Add storageclass template with diff api version

authorization/scc/tc538262/PodSecurityPolicySubjectReview_privileged_false.json, authorization/scc/tc538262/PodSecurityPolicySubjectReview_privileged_true.json, authorization/scc/tc538263/PodSecurityPolicySubjectReview.json, deployment/deployment-perme-failed-1.yaml, deployment/deployment-perme-failed-2.yaml, deployment/deployment-perme-failed-3.yaml, deployment/deployment1.json, deployment/updatev1.json
@xxing Could you please help review and merge,  thanks.
=> update quota for online env 

persistent-volumes/misc/pvc-with-stable-annotations.json
Template file used for storageclass api change test
=> Add pvc template with stable annotations

pods/allinone-volume/allinone-collisions-pod-1.yaml, pods/allinone-volume/allinone-collisions-pod-2.yaml, pods/allinone-volume/allinone-negative-pod-1.yaml, pods/allinone-volume/allinone-negative-pod-2.yaml, pods/allinone-volume/allinone-no-keypath-pod.yaml, pods/allinone-volume/allinone-normal-pod.yaml, pods/allinone-volume/allinone-opposite-path-pod.yaml, pods/allinone-volume/allinone-permission-mode-pod.yaml, pods/allinone-volume/allinone-same-path-pod.yaml, pods/allinone-volume/configmap-with-samekey.yaml, pods/allinone-volume/configmap.yaml, pods/allinone-volume/secret.yaml
@mdshuai please help to merge. Thx.
=> push allinone test files

image/db-templates/mongodb-26-rhel7-env-test.json
@wzheng1 
since `MONGODB_NOPREALLOC` env is DEPRECATED, update template, please help review, thx
=> update db template for ocp-12044

authorization/scc/tc538264/PodSecurityPolicyReview.json
@wanghaoran1988 please help merge this file updated for OCP 3.6 verison.
=> Update for OCP 3.6 version

pods/sysctls/pod-sysctl-unsafe-invalid1.yaml, pods/sysctls/pod-sysctl-unsafe-invalid2.yaml, pods/sysctls/pod-sysctl-unsafe-invalid3.yaml
@mdshuai Added some test files for sysctl test. Please help to merge. Thx.
=> add test files for sysctl test

authorization/scc/tc538262/PodSecurityPolicySubjectReview_privileged_false.json, authorization/scc/tc538262/PodSecurityPolicySubjectReview_privileged_true.json, authorization/scc/tc538263/PodSecurityPolicySubjectReview.json, deployment/deployment-perme-failed-1.yaml, deployment/deployment-perme-failed-2.yaml, deployment/deployment-perme-failed-3.yaml, deployment/deployment1.json, deployment/updatev1.json, quota/application-template-with-resources.json, templates/tc511599/job.yaml
@wanghaoran1988 Could you help review and merge ? thank you !
=> update for online3.6 failed cases

pods/sysctls/pod-sysctl-unsafe.yaml
@mdshuai Please help to review and merge. Thanks.
=> add more test files for sysctl

networking/aosqe-pod-for-ping.json, networking/list_for_pods.json, routing/abrouting/caddy-docker-2.json, routing/abrouting/caddy-docker-3.json, routing/abrouting/caddy-docker.json, routing/caddy-docker-2.json, routing/caddy-docker.json
remove the cpu limits setting since it is useless (cpu is calculated from memory) in all online env.
@bmeng please help review and merge. thx
=> update pod memory limist to 340Mi to adapt online-stg env

networking/egress-ingress/dns-egresspolicy1.json, networking/egress-ingress/dns-egresspolicy2.json, networking/egress-ingress/dns-invalid-policy1.json, networking/egress-ingress/dns-invalid-policy2.json, networking/egress-ingress/dns-invalid-policy3.json
Create five test files for https://trello.com/c/yH9l0ouV dns name with egress policy
=> Test files for dns name with egress policy

routing/reencrypt/reencrypt-without-all-cert.yaml
add this file to test reencrypt route without specified destinationCA
=> [networking]add reencrypt without all cert file

configmap/cmap-for-env.yaml
add cmap-for-env.yaml for ocp-13201
=> add cmap-for-env.yaml for ocp-13201

sysctls/pod-sysctl-safe.yaml
add following for ocp-10962
1. mkdir sysctls
2. add sysctls/pod-sysctl-safe.yaml
=> 1. mkdir sysctls

configmap/envfrom-cmap.yaml, sysctls/net_ipv4_tcp_syncookies.yaml
configmap/envfrom-cmap.yaml for ocp-13201
sysctls/net_ipv4_tcp_syncookies.yaml for ocp-10962
=> add follwoing files:

pods/emtydir-host.yaml, pods/securityContext/container-selinux.yaml, pods/securityContext/pod-selinux.yaml
=> add test files for selinux testing

pods/securityContext/both-level.yaml, projects/invalid-namespace.yaml, projects/ns1.yaml, projects/valid-namesapce.yaml
@mdshuai  Please help to merge. Thx.
=> add both level selinux test file

projects/invalid-namespace.yaml, projects/valid-namesapce.yaml
=> update test files for node selector

scheduler/taint-toleration/pod-toleration-fail-effect.yaml, scheduler/taint-toleration/pod-toleration-fail-operator.yaml, scheduler/taint-toleration/pod-toleration-fail-second-no.yaml, scheduler/taint-toleration/pod-toleration-fail-second-prefer.yaml, scheduler/taint-toleration/pod-toleration.yaml
@mdshuai  5 taint toleration test yaml files added.
please review and merge.
Thanks.
=> add 5 taint toleration test yaml files

scheduler/taint-toleration/pod-toleration-fail-operator.yaml
=> modify pod name to keep name style consistent with others

pods/initContainers/Promote_InitContainers/init-containers-fail.yaml, pods/initContainers/Promote_InitContainers/init-containers-readiness.yaml, pods/initContainers/Promote_InitContainers/pod-init-containers-always-fail.yaml, pods/initContainers/Promote_InitContainers/pod-init-containers-always-succ.yaml, pods/initContainers/Promote_InitContainers/pod-init-containers-deadline.yaml, pods/initContainers/Promote_InitContainers/pod-init-containers-loop.yaml, pods/initContainers/Promote_InitContainers/pod-init-containers-never-fail.yaml, pods/initContainers/Promote_InitContainers/pod-init-containers-never-succ.yaml, pods/initContainers/Promote_InitContainers/pod-init-containers-onfailure-fail.yaml, pods/initContainers/Promote_InitContainers/pod-init-containers-onfailure-succ.yaml, pods/initContainers/Promote_InitContainers/pod-init-containers-qos.yaml, pods/initContainers/Promote_InitContainers/pod-init-containers-quota1.yaml, pods/initContainers/Promote_InitContainers/pod-init-containers-success.yaml, pods/initContainers/Promote_InitContainers/pod-init-containers-volume.yaml, pods/initContainers/Promote_InitContainers/quota.yaml, pods/initContainers/Promote_InitContainers/resolv.conf
@mdshuai Please help to merge. Thanks
=> add test files for Promote Init Containers to GA Test

online/clusterinfra/deploymentconfig-with-nodename.yaml, online/clusterinfra/pod-with-nodename.yaml
@mdshuai Please help review and merge, thanks a lot.
=> Add test files to repository for the test cases OCP-9788 and OCP-9903

authorization/scc/tc538262/PodSecurityPolicySubjectReview_privileged_false.json, authorization/scc/tc538262/PodSecurityPolicySubjectReview_privileged_true.json, authorization/scc/tc538263/PodSecurityPolicySubjectReview.json, deployment/deployment-perme-failed-1.yaml, deployment/deployment-perme-failed-2.yaml, deployment/deployment-perme-failed-3.yaml, deployment/deployment1.json, deployment/updatev1.json, quota/application-template-with-resources.json, replicaSet/tc533162/rs_endpoints.yaml, templates/tc511599/job.yaml
@xxing  Could you please help review and merge, thank you!
=> update limit for  replicaSet/tc533162/rs_endpoints.yaml

networking/egressnetworkpolicy/internal-policy.json
@bmeng please help review and merge, thx
=> add file internal-policy.json to egressnetworkpolicy

pods/tolerations/toleration-noexecute.yaml
=> add taint test files

pods/tolerations/pod-dedicated-nodes.yaml, pods/tolerations/pod-no-toleration.yaml, pods/tolerations/pod-no-toleration1.yaml, pods/tolerations/pod-with-2tolerations.yaml, pods/tolerations/pod-with-toleration-dedicated-prefer.yaml, pods/tolerations/pod-with-toleration-dedicated.yaml, pods/tolerations/pod-with-toleration-red-prefer.yaml, pods/tolerations/pod-with-toleration-red.yaml, pods/tolerations/pod-with-toleration.yaml, pods/tolerations/pod-with-toleration1.yaml, pods/tolerations/pod-with-wildcard-toleration.yaml
@mdshuai Please help to review and merge. Thx.
=> add tolerations test files

persistent-volumes/azure/stable-storage.yaml
=> Add a stress test file for azure disk

persistent-volumes/gce/pv-with-annotations.json, persistent-volumes/gce/pv-with-storageClassName.json
Template used to auto test case OCP-1367{2..5}
=> Add PV template with annations/storageClassName

rc/idle-rc-1.yaml, rc/idle-rc-2.yaml
@mdshuai please review and merge. Thanks.
=> fix11633 for online quota limitation

groups/ad_paging.yaml, groups/ead_paging.yaml, groups/rfc2307_paging.yaml, groups/sync-config-tolerating.yaml
@wsun1 would you please help merge this? thx.
=> add files for OCP-11244

online/imagestream/skopeo.json
@zhouying7780 please help review the json file , thanks.
=> add skopeo pod json file

pods/initContainers/Promote_InitContainers/pod-init-containers-deadline.yaml, pods/initContainers/Promote_InitContainers/pod-init-containers-quota2.yaml, pods/initContainers/Promote_InitContainers/pod-init-containers-volume.yaml
=> update test files for init containers

configmap/efsconfigm.yaml
=> Add a configmap file for efs-provisioner

networking/service-externalName.json
Create service-externalName.json for automating OCP-15004
@bmeng @lihongan @duyanyan @zhaozhanqi
=>  [networking] Create service-externalName.json

pods/maximum-dead-containers-per-container.yaml
@mdshuai Please help to review and merge. Thx.
=> add test file for dead containers testing

pods/initContainers/pod-init-containers-beta.yaml, pods/initContainers/pod-init-containers-qos.yaml
@mdshuai please help merge yaml files for auto. thanks.
=> add init container feature pod yaml files for auto

pods/tolerations/tolerationSeconds.yaml
=> add test file for toleration test

scheduler/taint-toleration/pod-with-toleration-fail-no-key.yaml, scheduler/taint-toleration/pod-with-toleration-fail.yaml
add test files to automate cases of taint toleration feature.
@mdshuai please review and merge. 
Thanks.
=> add test files to automate cases of taint toleration feature

templates/OCP-15196/limitrange.json
=> add limit range template for OCP-15196

downwardapi/dapi-resources-env-magic-keys-pod-without-requests.yaml
Decrease the limit value in yaml file: dapi-resources-env-magic-keys-pod-without-requests.yaml
=> Decrease the limit value

infrastructure/podpreset/configmap.yaml, infrastructure/podpreset/hello-pod.yaml, infrastructure/podpreset/podpreset-configmap.yaml, infrastructure/podpreset/podpreset-simple.yaml
@mdshuai please review and merge test files for podpreset feature.
Thanks.
=> add test files for podpreset feature

pods/seccomp/pod-sec-two-cont.yaml
=> Add a seccomp test file

pods/seccomp/pod-sec-pod-prof2.yaml, pods/seccomp/pod-sec-two-cont-1.yaml, pods/seccomp/pod-sec-two-cont-2.yaml, pods/seccomp/pod-sec-two-cont-3.yaml
=> update secc test files

pods/allinone-volume/allinone-collisions-pod-1.yaml, pods/allinone-volume/allinone-collisions-pod-2.yaml, pods/allinone-volume/allinone-negative-pod-1.yaml, pods/allinone-volume/allinone-negative-pod-2.yaml, pods/allinone-volume/allinone-no-keypath-pod.yaml, pods/allinone-volume/allinone-normal-pod.yaml, pods/allinone-volume/allinone-opposite-path-pod.yaml, pods/allinone-volume/allinone-permission-mode-pod.yaml, pods/allinone-volume/allinone-same-path-pod.yaml
old image [failed in online](http://ci-qe-openshift.nay.redhat.com/userContent/cucushift/v3/2017/08/10/02:55:27/Project_secrets_configmap_and_downward_API_into_the_same_volume_with_normal_keys_and_path/console.html)
=> update image for allinone-volome pod

infrastructure/cluster-capacity/cluster-capacity-pod.yaml, infrastructure/cluster-capacity/cluster-capacity-rc.yaml, infrastructure/cluster-capacity/clusterquota-pod1.yaml, infrastructure/cluster-capacity/clusterquota-pod2.yaml, infrastructure/cluster-capacity/limit-pod1.yaml, infrastructure/cluster-capacity/limit-pod2.yaml, infrastructure/cluster-capacity/limit-pod3.yaml, infrastructure/cluster-capacity/limits.yaml, infrastructure/cluster-capacity/namespace.yaml, infrastructure/cluster-capacity/nodename-pod1.yaml, infrastructure/cluster-capacity/ns-pod1.yaml, infrastructure/cluster-capacity/ns-pod2.yaml, infrastructure/cluster-capacity/simple-pod1.yaml, infrastructure/cluster-capacity/simple-pod2.yaml, infrastructure/cluster-capacity/simple-pod3.yaml
=> add cluster-capacity test files

scheduler/node-affinity/node-affinity-required-us.yaml, scheduler/node-affinity/node-anti-affinity-required.yaml
@mdshuai help review & merge. Thanks.
=> add affinity test files for automation

infrastructure/cluster-capacity/cluster-capacity-role.yaml
=> add cluster capacity file

cli/OCP-11049/invalid.json, cli/OCP-11049/invalid.yaml
add two negative test file
@yapei
=> add two negative test file

scheduler/pod-affinity/pod-pod-affinity-exists.yaml, scheduler/pod-affinity/pod-pod-affinity-multi-matchexpressions.yaml, scheduler/pod-affinity/pod-pod-affinity-s1.yaml, scheduler/pod-affinity/pod-s1.yaml
@mdshuai help review and merge. Thanks.
=> Add pod yaml files for pod-affinity auto test

infrastructure/hpa/dc-hello-hpa.yaml, infrastructure/hpa/hello-pod.yaml, infrastructure/hpa/rc-hello-hpa.yaml
@mdshuai Help to merge. Thanks.
=> add hpa v1 test files

build/tc14373/test-valuefrom.json, build/tc14381/test-valuefrommap.json
Add test files for cases with valuefrom feature
=> Add tc14373 and tc14381 cases test files

scheduler/node-affinity/node-affinity-preferred-case14509.yaml
@mdshuai please help review and merge.
Thanks.
=> add file for auto case14509

scheduler/node-affinity/node-affinity-required-case14478.yaml, scheduler/node-affinity/node-affinity-required-case14479.yaml, scheduler/node-affinity/node-affinity-required-case14488.yaml, scheduler/node-affinity/node-anti-affinity-required-case14480.yaml, scheduler/node-affinity/node-anti-affinity-required-case14484.yaml
@mdshuai help review and merge.
Thanks.
=> seperate test files to decouple

job/max-dead-containers.yaml, limits/limitrange.yaml, pods/seccomp/pod-sec-pod-prof1.yaml, templates/create-bootstrap-quota-limit-template.yaml
=> Add test files for automation

scheduler/pod-affinity/pod-pod-affinity-proj-case14697.yaml
@mdshuai  help review and merge. Thanks.
=> add pod-affinity file for automating case14697

scheduler/node-affinity/pod-multiple-match-expressions-case14576.yaml, scheduler/node-affinity/pod-multiple-match-expressions-case14577.yaml
@mdshuai please review and merge.
Thanks.
=> add yaml files for automating case 14576, 14577

services/standalone-service.json
=> Template for OCP-10101/

persistent-volumes/misc/storageClass-zones.yaml
@jhou1  Template file used to test card https://trello.com/c/hIoJFosv/506-8-admins-can-configure-zones-in-storage-class
=> Add storageclass template with parameter zones

routing/idle/long-readiness-pod.json
@bmeng, please help review and merge.  Thanks
=> rc with long readiness pod

quota/resourceQuota-counts.yaml
=> Add a resourceQuota for pvc counts

scheduler/pod-affinity/pod-pod-affinity-proj-case14697.yaml
@mdshuai  please review and merge.
Thanks.
=> use random project rather than hardcoded one

scheduler/node-affinity/pod-node-affinity-selector-case14556.yaml, scheduler/node-affinity/pod-node-affinity-selector-case14557.yaml, scheduler/node-affinity/pod-node-affinity-selector-case14566.yaml, scheduler/node-affinity/pod-node-affinity-selector-terms-case14568.yaml
@mdshuai please review and merge. Thanks.
=> add test files for node affinity feature

scheduler/node-affinity/node-affinity-gt4-required-case14522.yaml, scheduler/node-affinity/node-affinity-lt6-required-case14525.yaml, scheduler/node-affinity/node-affinity-required-exists-case14520.yaml, scheduler/node-affinity/node-anti-affinity-required-exists-case14521.yaml, scheduler/node-affinity/pod-node-affinity-selector-case14556.yaml, scheduler/node-affinity/pod-node-affinity-selector-case14557.yaml, scheduler/node-affinity/pod-node-affinity-selector-case14566.yaml, scheduler/node-affinity/pod-node-affinity-selector-terms-case14568.yaml
@mdshuai help review and merge. Thanks.
=> Nodeaffinity

scheduler/node-affinity/node-affinity-lt6-required-case14525.yaml
=> correct typo

extensions/system-status.js, extensions/system-status.json
@yapei Please help to merge, thanks!
=> Add js and json files for system-status

templates/test-api.yaml
Fix OCP-10775. See cucushift PR 5421 for details
@yapei help merge
=> Fix OCP-10775

infrastructure/podpreset/pod-no-podpreset.yaml
@mdshuai  Help review and merge, Thanks.
=> yaml file for automating OCP15055

svc-catalog/ups-broker-3.7.yaml, svc-catalog/ups-broker-deploy.yaml, svc-catalog/ups-broker-svc.yaml, svc-catalog/ups-instance-1.yaml, svc-catalog/ups-instance-2.yaml, svc-catalog/ups-instance.yaml, svc-catalog/ups-serviceinstancecredential-1.yaml, svc-catalog/ups-serviceinstancecredential-2.yaml, svc-catalog/ups-serviceinstancecredential.yaml
@mdshuai Please help to merge. Thanks.
=> add svc-catalog test files

svc-catalog/ups-broker-3.7.yaml, svc-catalog/ups-broker-deploy.yaml, svc-catalog/ups-instance-1.yaml, svc-catalog/ups-instance-2.yaml, svc-catalog/ups-instance.yaml, svc-catalog/ups-servicebinding-1.yaml, svc-catalog/ups-servicebinding-2.yaml, svc-catalog/ups-servicebinding.yaml, svc-catalog/ups-serviceinstancecredential.yaml
=> update svc-catalog test files

templates/tc517666/ruby22rhel7-template-sti.json, templates/tc517667/ruby22rhel7-template-sti.json
=> reduce pods number to adjust online quota limitation

templates/tc467937/pod467937-new.yaml
@wsun1 , new yaml file for fit the design change in ocp 3.7 and later version, thx
=> pod467937-new for ocp 3.7 and later version

persistent-volumes/snapshot/claim.yaml, persistent-volumes/snapshot/snapshot-role.yaml, persistent-volumes/snapshot/snapshot.yaml, persistent-volumes/snapshot/storageclass.yaml
Those files are used during snapshot feature testing.
=> Add test file for snapshot feature

templates/ui/application-template-dockerbuild-without-customize-route.json, templates/ui/application-template-dockerbuild.json, templates/ui/application-template-stibuild-without-customize-route.json, templates/ui/application-template-stibuild.json
Keep templates with and without custom route
=> add template without custom route for ui

svc-catalog/ups-instance-1.yaml, svc-catalog/ups-instance-2.yaml, svc-catalog/ups-instance.yaml
@mdshuai Help to merge. Thanks.
=> update serviceinstance test files

routing/reencrypt/reen-2pods-without-all-cert.yaml
@bmeng please help review and merge
=> add reen-2pods-without-all-cert.yaml for cookie testing

routing/header-test/header-reecrypt-without-CA.json
Add this json file for testing header of reencrypt route without cert file
=> add header test for reencrypt without CA

routing/reencrypt/two-caddy-with-serving-cert.yaml
@bmeng please help review and merge
=> add two-caddy-with-serving-cert.yaml (2pods, svc and configmap)

deployment/hello-deployment-oso.yaml
@wanghaoran1988 @wsun1 , update the deployment file for oso env with limited resource(such as: 1-2 pod limitation). thx
=> hello-deployment for oso with limited resource(pod number)

build/build-postcommit.json
@yapei Please review and merge, thanks!
=> Add a bc json for postcommit without trigger it for init

templates/OCP-11417/ruby22rhel7-template-docker-fail-to-push.json, templates/OCP-11417/ruby22rhel7-template-docker-wrong-builder-image.json, templates/OCP-11417/ruby22rhel7-template-docker-wrong-post-commit.json, templates/OCP-11417/ruby22rhel7-template-docker.json, templates/OCP-11417/ruby22rhel7-template-sti-wrong-source.json, templates/OCP-11417/ruby22rhel7-template-sti.json, templates/OCP-11417/test-buildconfig-wrong-scripts.json, templates/OCP-11417/test-buildconfig.json
Add test template file for OCP-11417
=> add test file for OCP-11417

svc-catalog/servicebinding-template.yaml, svc-catalog/serviceinstance-parameters-template.yaml, svc-catalog/serviceinstance-template.yaml
@mdshuai Help to merge. Thanks.
=> add asb template files

rbac/OCP-12989/role.json, rbac/OCP-12989/rolebinding.yaml
Add some test files for roles related features @wanghaoran1988 could you please help review and merge?
=> add test file for roles

svc-catalog/ups-binding-template.yaml, svc-catalog/ups-broker-template.yaml, svc-catalog/ups-instance-template.yaml
@mdshuai Help to merge. Thanks.
=> add ups broker relate templates

templates/OCP-13487/test-template.json
@yapei, pls help merge, thanks!
=> Add testfile for OCP-13487

dockerfiles/README.md, dockerfiles/squid-proxy/latest/Dockerfile, dockerfiles/squid-proxy/latest/entrypoint.sh, dockerfiles/squid-proxy/latest/htpasswd, dockerfiles/squid-proxy/latest/squid_auth.conf
Opening this PR per https://github.com/openshift/cucushift/pull/4453#issuecomment-346800647 and https://github.com/openshift/cucushift/pull/4453#discussion_r153007266 
For updated contents, see diff in https://gist.github.com/xingxingxia/5e5ca36bc4978f4d143bbb08f08a6900
=> Update aosqe/squid-proxy Dockerfile to support authentication for TC OCP-11564 auto

svc-catalog/ups-binding-template.yaml
@mdshuai help to merge. Thanks.
=> Update ups-binding template

extensions/external-logging.js
@yapei pls help merge for https://github.com/openshift/cucushift/pull/5745, thank you
=> Add extensions js for OCP-11024 other external logging

cli/oc_plugin/myplugin/plugin.yaml
@yapei pls help review per https://github.com/openshift/cucushift/pull/5729#discussion_r157515731, thx
=> Add oc plugin stuff for OCP-14854 auto

persistent-volumes/misc/storageClass-noProvisioner.yaml
Negative testing for storage class creation without provisioner.
=> Test file for storageclass creation without provisioner

job/cronjob_3.9_with_startingDeadlineSeconds.yaml
@haowang, scheduledjob -> cronjob in ocp 3.9, thx
=> cronjob_3.9_with_startingDeadlineSeconds

pipeline/samplepipeline.yaml, pipeline/ui-pipeline-stage.yaml
@yapei pls help to merge, thx!
=> Add pipeline testfile

persistent-volumes/secret/secret-pod-test.json
=> Switch to image which contains bash

persistent-volumes/azure/azsc-Default.yaml, persistent-volumes/hostpath/emptpropa.yaml, persistent-volumes/hostpath/propaprivate.yaml, persistent-volumes/hostpath/propashare.yaml, persistent-volumes/hostpath/propaslave.yaml, persistent-volumes/hostpath/unprishare.yaml, persistent-volumes/hostpath/unprislave.yaml
=> Add propagation test files

persistent-volumes/misc/pod-overlap-path.yaml
Test file for pod with overlapped mount point.
=> Add pod with overlapped mount point

persistent-volumes/nfs/initcontainer-blockvolume-pod.yaml
@jhou1 please help review and merge, thx.
=> Add a pod yaml file for blockvolume test

registry/config.yml
=> add default docker registry config file

quota/application-template-with-resources.json
@wanghaoran1988 pls help to merge it, thx
=> fix_template

pods/pv-scrubber.json
@jhou1  Update template to be used to automate test case OCP-9696/9697/10519
=> Update recycler template

extensions/system-status.js
=> Update extension script for using directly in configmap

quota/application-template-with-resources.json
@wanghaoran1988 , template change from ruby-20-centos7 to ruby-22-centos7, thx
=> Fix template

persistent-volumes/iscsi/pod-two-luns.json
@jhou1 please help review and merge.
=> Modify yaml file for case OCP-10143

build/test-buildconfig.json, templates/tc479059/application-template-parameters.json
=> use ruby23 as the base image

logging_metrics/OCP-16138/inventory, logging_metrics/default_inventory_uninstall_prometheus, networking/egress-ingress/dns-egresspolicy3.json, persistent-volumes/azure/azsc-DEACCT.yaml, persistent-volumes/azure/azsc-DEDICATE.yaml, persistent-volumes/azure/azsc-DESKU.yaml, persistent-volumes/azure/azsc-MANAGED.yaml, persistent-volumes/azure/azsc-SKUACCT.yaml
=> Added some azure test files

persistent-volumes/azure-file/azf-pv.yml, persistent-volumes/azure-file/azf-pvc.yaml, persistent-volumes/azure-file/azfpvc-sc.yaml, persistent-volumes/azure-file/azfpvcpod.yaml, persistent-volumes/azure-file/azfsc-MODIR.yaml, persistent-volumes/azure-file/azfsc-MOUID.yaml, persistent-volumes/azure-file/azfsc-NOPAR.yaml, persistent-volumes/azure-file/azpvcpod.yaml, persistent-volumes/azure-file/azure-secret.yaml, persistent-volumes/azure/azsc-DEACCT.yaml, persistent-volumes/azure/azsc-DEDICATE.yaml, persistent-volumes/azure/azsc-DESKU.yaml, persistent-volumes/azure/azsc-MANAGED.yaml, persistent-volumes/azure/azsc-SKUACCT.yaml
=> Add azure related test files

logging_metrics/playbooks/externalserver.yml, logging_metrics/playbooks/internal-forward-fluentd.yml, logging_metrics/playbooks/internal-rsyslog.yml, logging_metrics/playbooks/roles/ocp_facts/README.md, logging_metrics/playbooks/roles/ocp_facts/defaults/main.yml, logging_metrics/playbooks/roles/ocp_facts/tasks/main.yml, logging_metrics/playbooks/roles/vm_type/README.md, logging_metrics/playbooks/roles/vm_type/defaults/main.yml, logging_metrics/playbooks/roles/vm_type/tasks/main.yml, logging_metrics/playbooks/templates/elasticsearch.service.j2, logging_metrics/playbooks/templates/elasticsearch.yml.j2, logging_metrics/playbooks/templates/forwardsecret.yml.j2, logging_metrics/playbooks/templates/internal-dc-forward-fluentd.yaml.j2, logging_metrics/playbooks/templates/internal-dc-rsyslog.yaml.j2, logging_metrics/playbooks/templates/internal-forward-fluent.conf.j2, logging_metrics/playbooks/templates/internal-forward-patch-recover.sh.j2, logging_metrics/playbooks/templates/internal-forward-patch.sh.j2, logging_metrics/playbooks/templates/patchfluentdsecuryforward.sh.j2, logging_metrics/playbooks/templates/rsyslog.conf.j2, logging_metrics/playbooks/templates/td-agent.conf.j2
@pruan-rht  @wsun1  Could we use playbooks as directory names?
=> add logging external server playbooks

extensions/catalog-categores.js
@yapei Please help to merge, thanks
=> Add js for OCP-14174

extensions/quota-message.js
@yapei Please help to merge, thanks
=> Add quota-message.js for OCP-15418

infrastructure/nodeselector/hello-pod-env-dev.yaml, infrastructure/nodeselector/hello-pod-env-dev2.yaml, infrastructure/nodeselector/hello-pod-env-qe.yaml
=> add 3 nodelector files for automation cases

persistent-volumes/azure-file/azfsc-ACONLY.yaml
=> Add a azure file storage class with account to fix Alex requirement

persistent-volumes/scaleio/pod.yaml, persistent-volumes/scaleio/secret.yaml
=> Add scaleio test files

routing/ingress/path-ingress.json, routing/ingress/test-ingress.json, routing/ingress/tls-ingress.json
since the service port is 27017 in https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/routing/edge/service_unsecure.json
so updated these to the correct port. 
@lihongan @bmeng  please help review and merge this. thanks
=> update the service port

quota/pod-quota.yaml
@yapei Add this file according to https://github.com/openshift/cucushift/pull/6139#discussion_r180684396 
Thanks!
=> Add a simple quota for pod number

templates/OCP-12057/application-template-stibuild_pull_private_sourceimage.json
Add a private sourceimage to template.
=> Add test file for  OCP-12057

image-streams/httpd-istag.yaml
@yapei This is for OCP-10349 categories test
=> Add a customized istag for ui test case

cli/oc_plugin/kube.yaml, cli/oc_plugin/kubectl_plugins_path.yaml, cli/oc_plugin/usr-share.yaml, cli/oc_plugin/xdg_data_dirs.yaml
@yapei please help merge for https://github.com/openshift/cucushift/pull/5995 , thanks
=> Add oc plugin yaml files

svc-catalog/ups-broker-deploy.yaml, svc-catalog/ups-broker-svc.yaml
As title shows, we add the option to display the ups-brokers' logs, please help to merge it.
=> Add an option to display logs in terminal

routing/tc/OCP-10894/caddy-docker-2.json, routing/tc/OCP-10894/caddy-docker.json, routing/tc/OCP-10894/service-unsecure-2.json, routing/tc/OCP-10894/service-unsecure-3.json, routing/tc/OCP-10894/service-unsecure-4.json, routing/tc/OCP-10894/service-unsecure.json
=> add test files for OCP-10894

quota/limits.yaml, quota/pod-with-resources.yaml
=> add test file for quota cases

online/pvc_storage.yaml
@yasun1 @yufchang Could anyone help to merge this please? Thanks!
=> Add a pvc for online auto

build/tc-OCP-17489/bc_webhook_triggers.yaml
@yapei please help merge. Locally passed for the OCP-17489 auto. Thanks
=> Add for OCP-17489

storage/localvolume/configmap.yaml
Copied from https://raw.githubusercontent.com/qinpingli/v3-testfiles/localvolume/persistent-volumes/localvolume/configmap.yaml
=> Add test file used for local volume testing

storage/snapshot/claim.yaml
=> Add require field for snapshot pvc

storage/snapshot/deployment-aws.yaml, storage/snapshot/deployment-gce.yaml
=> Use snapshot images that's under testing

image-streams/ui-netcore-is.json
=> add is testfile for ui

image/jenkins-slave-configmap.yaml
=> add configmap template for jenkins slave

storage/misc/pod-with-block-volume.yaml
@jhou1 @qinpingli 
Copied from pod.yaml. 
Note the different part is ```volumeDevice/devicePath```.
May need to update the image with a proper one to contain the necessary tools used.
=> Add pod template for block volume test

storage/azure-file/azf-role.yaml, storage/azure-file/azf-rolebind.yaml
=> Add azure file role and rolebinding file

svc-catalog/ups-broker-template.yaml
add 'alsologtostderr' param for ups-broker deployment to check ups-broker pod in cases.
@pruan-rht @chengzhang1016 @jianzhangbjz  please help review.
=> add alsologtostderr param for ups-broker to check log

routing/routetimeout/httpbin-pod.json
adding two containers into one pod to support both http and https access.
@bmeng please help review.
=> update httpbin-pod to support both http and https in one pod

replicaSet/tc536594/replicaset-with-two-containers.yaml
=> update testfil's resource

registry/ocp-14179/config.yml
=> add registry config file for OCP-14179

storage/nfs/nfs-server.yaml
@jhou1 Please review and merge.
This PR can fix nfs auto cases can not run on overlay2 evn.
=> nfs server test file

registry/ocp-18559/prometheus-role.yaml
=> add cluster role file for ocp-18559

svc-catalog/servicebindings/bind1.yaml, svc-catalog/servicebindings/bind2.yaml, svc-catalog/servicebindings/bind3.yaml, svc-catalog/servicebindings/bind4.yaml, svc-catalog/servicebindings/bind5.yaml, svc-catalog/servicebindings/bind6.yaml
Added some fake `servicebindings` so that the returned secrets by ASB including some specical keys.
=> add some test servicebindings files

svc-catalog/serviceinstance-lastop-template.yaml
@jhou1 Could you help to merge? Thanks.
=> add template for lastop

storage/localvolume/configmap.yaml
@bmeng Could you help merge this PR?
=> update configmap.yaml for localvolume test

storage/csi/cinder-clusterrole.yaml, storage/csi/cinder-clusterrolebinding.yaml, storage/csi/cinder-daemonset.yaml, storage/csi/cinder-deployment.yaml, storage/csi/cinder-secrets.yaml, storage/csi/cinder-storageclass.yaml
@jhou1 Please help merge this PR.
=> Add yaml files for csi cinder driver

storage/csi/cinder-daemonset.yaml
@jhou1 please help merge this pr for fix this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1610709
=> Remove nodeselector from daemonset

online/mysql-limit.yaml
The file is used to limit&emptyDir testing on online.
=> upload a file for limit&emptyDir testing

online/hello-pod-limit.yaml
@jhou1 @mdshuai  Please help merge the file which is used for online testing.
=> add hello-pod-limit.yaml for online testing

pods/tolerations/pod-with-toleration-empty-operator.yaml
add a test file for OCP-20046.
=> add testcase OCP-20046

build/OCP-20221/mysecret.yaml
=> Add secret file for case OCP-20221

svc-catalog/ups-binding-rename-template.yaml
As title, please help to merge it. @mdshuai @akostadinov Thanks!
=> add a template to create the servicebinding which can rename keys

cases/OCP-10674/ruby-ex/README.md, cases/OCP-10674/ruby-ex/config.ru, templates/OCP-11007/cakephp.json, templates/OCP-11007/cakephp1.json, templates/OCP-11007/cakephp2.json, templates/OCP-11007/cakephp3.json, templates/OCP-11007/cakephp4.json
=> Update some urls

pipeline/OCP-17358/jenkinsslave-jdk.yaml, pipeline/OCP-17366/jenkinsslave-javaenv.yaml
=> Add jenkins autofiles

deployment/OCP-11384/application-template-stibuild.json
@xingxingxia  Could you help merge ? thanks.
=> update script for ocp-11384

deployment/build-deploy-without-configchange.json
@xingxingxia  please help merge , thanks.
=> update script for ocp-11790

build/ruby20-imageupgrade-stibuild.json, build/tc470322/test-template.json, build/tc470322/test-template_2.json, build/tc476349/ruby20rhel7-template-sti.json, secrets/tc482191/ssh-secret-ruby22rhel7-template-sti.json, templates/OCP-11417/ruby22rhel7-template-docker-fail-to-push.json, templates/OCP-11417/ruby22rhel7-template-docker-wrong-builder-image.json, templates/OCP-11417/ruby22rhel7-template-docker-wrong-post-commit.json, templates/OCP-11417/ruby22rhel7-template-docker.json, templates/application-template-stibuild.json, templates/tc498847/tc498847-docker.json, templates/tc498848/tc498848-s2i.json, templates/tc519486/django-postgresql.json, templates/tc519486/django.json, templates/tc525738/application-template-stibuild.json, templates/tc544375/ruby22rhel7-template-docker.json.failtopush
@wewang58 @zhouying7780 I see you do this in several PRs recently. So i updated the others via shell script. Please take a look.
=> Update args to script to fit for 4.0

storage/nfs/nfs-server.yaml
Helps https://github.com/openshift/BushSlicer/pull/17
Hold on merging, review BushSlicer pr first.
=> Use emptyDir volume for nfs-server

logging/3.x/checkinges, logging/3.x/createindices.sh, logging/3.x/gatherlogging, logging/3.x/refresh_curator.sh, logging/debughelp, logging/es_checkings, logging/loggen/json_log_apps.json, logging/loggen/jsonloggen.sh, logging/loggen/loggen.sh, logging/loggen/syslogen.sh, logging/record_example/container_rsyslog_imjournal.example, logging/record_example/container_rsyslog_jsonfile.example
@wsun1  @yapei  The PR include some script and example in logging testing. Could you help me to Merge them?
=>  logging scripts, debug, records example

logging/es_checkings
@pruan-rht  Could you help me merge the fix?
=> fix oc exec error

networking/headless_notreadypod.json
add headless svc and  check the ep can be published the not ready pod
=> add headless for not ready pod

storage/nfs/nfs-server.yaml
Not sure why https://github.com/openshift-qe/v3-testfiles/pull/949 is lost.
@jhou1 @weherdh
=> Re-submit PR #949

logging/clusterlogging/customresource-fluentd.yaml, logging/clusterlogging/customresource-rsyslog.yaml, logging/clusterlogging/existingvolume.yaml, logging/clusterlogging/multipleredundancy.yaml, logging/clusterlogging/storageclass_default.yaml, logging/clusterlogging/storageclass_name.yaml
@liangxia  Could you help me merge this files.
=> Fix name and format issue

logging/clusterlogging/zeroredundancy.yaml
@jianlinliu  @akostadinov  Could you help me merge these files? Thanks
=> Add zeroredundancy.yaml and use same node number 3 for all redundancy

routing/dns/externalname-service-ext.json, routing/dns/externalname-service-int.json, routing/dns/headless-services.json
@bmeng  Please help review and merge. thanks
=> add test files for dns

logging/clusterlogging/nodeSelector.yaml, logging/clusterlogging/storageclass_name.yaml
=> Logging nodeSelector template and bug fix

logging/clusterlogging/example.yaml, logging/clusterlogging/example_unmanaged.yaml, logging/clusterlogging/fullredundancy.yaml, logging/clusterlogging/multipleredundancy.yaml, logging/clusterlogging/nodeSelector.yaml, logging/clusterlogging/singleredundancy.yaml, logging/clusterlogging/storageclass_default.yaml, logging/clusterlogging/storageclass_name.yaml, logging/clusterlogging/zeroredundancy.yaml
@yapei  Could you help merge these files?
=>  limit resource for test purpose

limits/limitrange-PodContainerImageISPvc.yaml
@yapei Please help to merge, thanks!
=> Add limitRange for different kinds of resources

logging/clusterlogging/customresource-fluentd.yaml, logging/clusterlogging/customresource-rsyslog.yaml, logging/clusterlogging/example.yaml, logging/clusterlogging/example_unmanaged.yaml, logging/clusterlogging/fullredundancy.yaml, logging/clusterlogging/multipleredundancy.yaml, logging/clusterlogging/nodeSelector.yaml, logging/clusterlogging/singleredundancy.yaml, logging/clusterlogging/storageclass_default.yaml, logging/clusterlogging/storageclass_name.yaml, logging/clusterlogging/zeroredundancy.yaml
@pruan-rht Could help me merge this pr.
=> use less resource

logging/clusterlogging/csc-clusterlogigng.yaml, logging/clusterlogging/csc-elasticsearch.yaml, logging/clusterlogging/namespace.yaml, logging/clusterlogging/openshift-logging-operator-group.yaml, logging/clusterlogging/sub-cluster-logging.yaml, logging/clusterlogging/sub-elasticsearch-operator.yaml
=> Add some important files to deploy logging in CLI

authorization/scc/scc-user-mustrunas.yaml
=> update scc-user-mustrunas file

logging/clusterlogging/customresource-fluentd.yaml, logging/clusterlogging/customresource-rsyslog.yaml, logging/clusterlogging/example.yaml, logging/clusterlogging/example_unmanaged.yaml, logging/clusterlogging/fullredundancy.yaml, logging/clusterlogging/multipleredundancy.yaml, logging/clusterlogging/nodeSelector.yaml, logging/clusterlogging/singleredundancy.yaml, logging/clusterlogging/storageclass_default.yaml, logging/clusterlogging/storageclass_name.yaml, logging/clusterlogging/zeroredundancy.yaml
@wzheng1  Could you help me merge the PR.
=> force to instance as resource name to following the changes

logging/clusterlogging/customresource-fluentd.yaml, logging/clusterlogging/nodeSelector.yaml
=> add resource for kibana-proxy and nodeSelector for fluentd

storage/fc/pv-default-rox.json, storage/fc/pv-recycle-rwo.json, storage/fc/pv-retain-rwx.json
@jhou1  @weherdh @chao007  Would you check ?
=> Update FC info to match QE's testing

logging/fluentdserver/fluentd_configmap_patch.yaml, logging/fluentdserver/fluentdserver_configmap.yaml
Update the fluentd server configmap
=> update configmap format

logging/fluentdserver/PasswordAuthentication/deploy.sh, logging/fluentdserver/PasswordAuthentication/fluentd_configmap_patch.yaml, logging/fluentdserver/PasswordAuthentication/fluentdserver_configmap.yaml, logging/fluentdserver/PasswordAuthentication/fluentdserver_deployment.yaml, logging/fluentdserver/TLSMutualAuthentication/deploy.sh, logging/fluentdserver/TLSMutualAuthentication/fluentdserver_configmap.yaml, logging/fluentdserver/TLSMutualAuthentication/fluentdserver_deployment.yaml, logging/fluentdserver/forward/deploy.sh, logging/fluentdserver/forward/fluentd_configmap_patch.yaml, logging/fluentdserver/forward/fluentdserver_deployment.yaml
Use different resource name for different type of foward
=> Update names in resource files

logging/fluentdserver/PasswordAuthentication/fluentdserver_deployment.yaml
=> overwrite the defaut fluentd config file

logging/fluentdserver/PasswordAuthentication/deploy.sh, logging/fluentdserver/TLSAutoGen/deploy.sh, logging/fluentdserver/TLSAutoGen/fluentd_configmap_patch.yaml, logging/fluentdserver/TLSAutoGen/fluentdserver_configmap.yaml, logging/fluentdserver/TLSAutoGen/fluentdserver_deployment.yaml, logging/fluentdserver/TLSEncryption/deploy.sh, logging/fluentdserver/TLSEncryption/fluentd_configmap_patch.yaml, logging/fluentdserver/TLSEncryption/fluentdserver_configmap.yaml, logging/fluentdserver/TLSEncryption/fluentdserver_deployment.yaml, logging/fluentdserver/TLSMutualAuthentication/deploy.sh, logging/fluentdserver/TLSMutualAuthentication/fluentdserver_configmap.yaml, logging/fluentdserver/TLSMutualAuthentication/fluentdserver_deployment.yaml, logging/fluentdserver/forward/deploy.sh
=> Fluentdserver

deployment/simple-deployment.yaml
Add a very simple deployment test file
=> add simple deployment yaml file

logging/fluentdserver/PasswordAuthentication/deploy.sh, logging/fluentdserver/forward/deploy.sh
=> redeploy fluentd pod by oc delete

logging/fluentdserver/PasswordAuthentication/fluentd_configmap_patch.yaml, logging/fluentdserver/PasswordAuthentication/fluentdserver_deployment.yaml, logging/fluentdserver/forward/fluentd_configmap_patch.yaml
=> use the defaut port 24224

logging/fluentdserver/PasswordAuthentication/fluentdserver_deployment.yaml, logging/fluentdserver/forward/fluentdserver_deployment.yaml
=> add label for different type of fluentdserver

logging/clusterlogging/customresource-fluentd.yaml
=> add kibana replicas

networking/networkpolicy/allow-namespace-and-pod.yaml
add allow namespaces and pod policy
@bmeng  could you help merge this, thanks
=> allow namespace and pod networkpolicy

upgrade_groupd.sh
@yapei @wzheng1 @anpingli @juzhao @pruan-rht  HI, please help to review your team‘s part code written in the script,  help to confirm again if there are any missing content and flaws in the script.
@pruan-rht  For the Metering part, I am really not sure if it's the right steps you want to prepare, please double confirm. 
Thank you all!
=> pre-upgrade script

logging/rsyslogserver/deploy.sh
=> fix the name error

routing/operator/ingresscontroller-test.yaml
@bmeng please help merge. thanks
=> add ingresscontroller

logging/tools/getOperatorSourceMetadata.sh, logging/tools/sync_images_to_internal_registry.sh
@QiaolingTang  Split to two files for the errata test use the first one to get images meta
=> Use the latest release version, and split to two files

storage/nfs/preboundpv-rwo.yaml
Add annotations part so that we can test annotations.
@jhou1
=> Add annotations to PV

storage/iscsi/README.md, storage/iscsi/iscsi.json, storage/iscsi/pod-with-iscsi.json, storage/iscsi/pv-rox.json, storage/iscsi/pv-rwo.json, storage/iscsi/pv-rwx.json, storage/iscsi/security/pv.json
=> Update iSCSI IQN to the one we are using

deployment/initcontainer.yaml
@yapei  could you help to merge? thanks.
=> add new test file

storage/csi-mock/claim.yaml, storage/csi-mock/csi-mock-driver.yaml, storage/csi-mock/pod.yaml, storage/csi-mock/readme
Templates used to test STOR-92
@jhou1
=> Add files for CSI testing

online/clusterinfra/deploymentconfig-with-nodename.yaml
Hey @yasun1 ,
Error message as below:
STDERR:
The DeploymentConfig "hello-openshift" is invalid: spec.template.spec.containers[0].ports[0].protocol: Unsupported value: "tcp": supported values: "SCTP", "TCP", "UDP"
So need to change protocol from tcp to TCP.
=> update protocol from tcp to TCP

online/dynamic_persistent_volumes/pvc-annotation-alpha.json, online/dynamic_persistent_volumes/pvc_gce.yaml, statefulset/stable-storage.yaml, statefulset/update-statefulset.yaml, storage/ebs/dynamic-provisioning-pvc.json, storage/gce/claim-rwo-dynamic.json, storage/misc/pvc-ERB.json, storage/misc/pvc.json
@chao007  for storage part
@jhou1  for statefulset part
@yasun1  for online part
=> Remove alpha annotation storage-class (obsoleted since 3.4)

routing/operator/ingressctl-namespace-selector.yaml, routing/operator/ingressctl-route-selector.yaml
@liangxia please help merge. thanks.
=> add two more ingresscontroller resources for shards

logging/tools/sync_images_to_internal_registry.sh
Reverts openshift-qe/v3-testfiles#1068
=> Revert "sync image using pod man"

logging/clusterlogging/deploy_clo_via_olm/4.1/04_clo_sub.yaml, logging/eleasticsearch/deploy_via_olm/4.1/05_eo-sub.yaml
=> adding labels for sub

build/forcePull/buildconfig-docker-ImageStream.json, build/forcePull/buildconfig-s2i-ImageStream.json, build/ruby22rhel7-template-docker.json, image/language-image-templates/OCP-13135/template.json, image/language-image-templates/OCP-13136/template.json, image/language-image-templates/ruby-rhel7-multivars.json, image/language-image-templates/tc521461/template.json, image/language-image-templates/tc521462/template.json, templates/tc476356/application-template-dockerbuild.json
=> Remove eol image

logging/tools/sync_images_to_internal_registry.sh
1. use oc image mirror
2. Support sha256 name
=> Fix image sync scripts

admin/subscription.yaml
@xingxingxia pls help to merge it, thx
=> etcdoperator_subscription

admin/etcd-cluster.yaml
@xingxingxia pls help for it, thx
=> etcd-cluster-yml

customresource/clidownload.yaml
=> add customize file for cli download urls

customresource/console-notification.yaml
=> Add yaml for ConsoleNotification

routing/abrouting/abwithrc_pod3.json, routing/abrouting/abwithrc_pod4.json, routing/abrouting/caddy-docker-2.json, routing/abrouting/caddy-docker-3.json, routing/abrouting/caddy-docker.json, routing/edge/list_for_edge.json, routing/passthrough/stickysession/pod_1.json, routing/passthrough/stickysession/pod_2.json, routing/reencrypt/list_for_reencrypt.json, routing/routetimeout/httpbin-pod-2.json, routing/routetimeout/httpbin-pod.json, routing/unsecure/list_for_unsecure.json, routing/websocket/pod.json, routing/wildcard_route/caddy-docker.json
Updating images to use aosqe repo.
=> update images url

cloud/machine-approver/create_csr.sh
=> Create pending csr

networking/multus-cni/Pods/generic_multus_pod_nodeselector.yaml
@pruan-rht 
modified:   networking/multus-cni/Pods/generic_multus_pod.yaml	
new file:   networking/multus-cni/Pods/generic_multus_pod_nodeselector.yaml
=> A file to add and a modifed one

networking/multus-cni/NetworkAttachmentDefinitions/bridge-host-local-vlan-200.yaml, networking/multus-cni/Pods/generic_multus_pod_nodeselector.yaml
=> Anothe file required as well

networking/multus-cni/NetworkAttachmentDefinitions/bridge-host-local-vlan-200.yaml, networking/multus-cni/NetworkAttachmentDefinitions/bridge-host-local-vlan.yaml, networking/multus-cni/Pods/generic_multus_pod_nodeselector.yaml
=> Last modifications as per multus tests requirement

networking/multus-cni/NetworkAttachmentDefinitions/bridge-host-local-vlan-200.yaml, networking/multus-cni/NetworkAttachmentDefinitions/bridge-host-local-vlan.yaml, networking/multus-cni/Pods/generic_multus_pod_nodeselector.yaml, networking/multus-cni/dnsmasq_for_testbridge.conf
@pruan-rht Can you merge, please? Thanks
=> dnsmasq conf file required for multus testbridge

deployment/build-deploy-without-configchange.json
@xingxingxia  Could you please review and help merge, thanks.
=> update ruby version for deploymentconfig

logging/logforwarding/elasticsearch/configmap.yaml, logging/logforwarding/elasticsearch/deployment.yaml, logging/logforwarding/elasticsearch/logforwarding-elasticsearch.yaml, logging/logforwarding/fluentd/insecure/configmap.yaml, logging/logforwarding/fluentd/insecure/fluentdserver_deployment.yaml, logging/logforwarding/fluentd/insecure/logforwarding-insecure.yaml, logging/logforwarding/fluentd/secure/configmap.yaml, logging/logforwarding/fluentd/secure/fluentdserver_deployment.yaml, logging/logforwarding/fluentd/secure/logforwarding-secure.yaml
@anpingli  I'm adding some files for the logforwarding test, PTAL, thanks.
=> add files for testing logforwarding

logging/logforwarding/clusterlogging.yaml, logging/logforwarding/elasticsearch/logforwarding-elasticsearch.yaml, logging/logforwarding/fluentd/insecure/configmap.yaml, logging/logforwarding/fluentd/insecure/logforwarding-insecure.yaml, logging/logforwarding/fluentd/secure/logforwarding-secure.yaml
=> add new file and change pipeline names

storage/iscsi/pod-direct-affinity.json, storage/iscsi/pod-direct.json
@chao007 @liangxia 
Failed log:
https://openshift-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Runner-v3/48563/consoleFull
=> Add files for OCP-13395

templates/tc476356/application-template-dockerbuild.json
@wzheng1 please help to merge it,thanks
=> Update ruby image to 2.5

routing/operator/ingressctl-tls-custom.yaml, routing/operator/ingressctl-tls-modern.yaml
adding two files for ingress TLS cipher testing
=> adding two files for ingress TLS cipher testing

online/dynamic_persistent_volumes/pvc-annotation-gp2.json
@yasun1 Please help review, thanks
=> Add pvc-annotation-gp2.json for case OCP-19480

routing/operator/ingressctl-tls-custom.yaml, routing/operator/ingressctl-tls-intmd.yaml, routing/operator/ingressctl-tls-old.yaml
@liangxia please help review and merge. thanks.
=> adding two more files for cipher

build/ruby20rhel7-template-sti.json, templates/OCP-12057/application-template-stibuild_pull_private_sourceimage.json
@wzheng1 pls help to merge it, thanks
=> Update ruby image

storage/rbd/dynamic-provisioning/user_secret.yaml, storage/rbd/rbd-secret.yaml, storage/rbd/security/rbd-secret.yaml
=> Bug 1781122, fix Ceph RBD secret type

logging/clusterlogging/multipleredundancy.yaml, logging/logforwarding/fluentd/insecure/fluentdserver_deployment.yaml, logging/logforwarding/fluentd/secure/configmap.yaml, logging/logforwarding/fluentd/secure/fluentdserver_deployment.yaml
=> remove namespace in LF files

logging/logforwarding/clusterlogging.yaml, logging/logforwarding/fluentd/insecure/fluentdserver_deployment.yaml, logging/logforwarding/fluentd/insecure/logforwarding-insecure.yaml, logging/logforwarding/forward_plugin/secure-forward-cm.yaml
@anpingli could you please help to merge it? Thanks a lot.
=> add new configmap and change fluentd image

customresource/console-external-log-link.yaml
@yapei Plz help to review and merge, thanks!
=> Add a template for console external log link

logging/logforwarding/elasticsearch/insecure/deployment.yaml, logging/logforwarding/elasticsearch/secure/deployment.yaml, logging/logforwarding/fluentd/insecure/fluentdserver_deployment.yaml, logging/logforwarding/fluentd/secure/fluentdserver_deployment.yaml
@anpingli could you please help to merge this PR? Thanks.
=> change api version for deployment files

logging/logforwarding/cert_generation.sh
The script is copied from https://github.com/openshift/cluster-logging-operator/blob/master/scripts/cert_generation.sh , I made some changes to make it easier to use for the logging test. 
@anpingli could you please help to merge this? Thanks a lot.
=> add script to generate certs

storage/secret/secret-pod-test.json
@chao007 @duanwei33  PTAL
Failed [log](http://ci-qe-openshift.usersys.redhat.com/userContent/cucushift/v3/2019/12/24/22:20:31/secret_volume_security_check/console.html)
Pass [log](https://privatebin-it-iso.int.open.paas.redhat.com/?2f2e8d158819ce5b#krUg8o6ucBsMCYJQnMutjinQqi9z6/xMNEu0VEdkGJo=)
=> Use image which contains SELinux

logging/clusterlogging/nodeSelector.yaml, logging/clusterlogging/nodeSelector_change.yaml, logging/clusterlogging/nodeSelector_override.yaml
Since different platform has different default storage class, so I removed the storage settings in the clusterlogging yaml files.
@anpingli could you please help to merge this PR? Thanks.
=> remove storage settings in the yaml files

storage/emptydir/emptydir_pod_selinux_test.json, storage/hostpath/security/hostpath.yaml
=> Fix image name

networking/multus-cni/NetworkAttachmentDefinitions/runtimeconfig-def-ip.yaml, networking/multus-cni/NetworkAttachmentDefinitions/runtimeconfig-def-ipandmac.yaml, networking/multus-cni/NetworkAttachmentDefinitions/runtimeconfig-def-mac.yaml, networking/multus-cni/Pods/runtimeconfig-pod-ip.yaml, networking/multus-cni/Pods/runtimeconfig-pod-ipandmac.yaml, networking/multus-cni/Pods/runtimeconfig-pod-mac.yaml
Update multus runtimeconfig files which will be used for my new multus scripts
@zhaozhanqi @huiran0826 @anuragthehatter @rbbratta
Please help to review, thanks!
=> runtimeconfig files

fips/fips-master-enable.yaml, fips/fips-worker-enable.yaml
add test files which enable fips using MCO
=> add fips enable test files

storage/aws-csi/manifest-4.3.yaml, storage/aws-csi/sc-encrypted.yaml, storage/aws-csi/sc-resize.yaml
Add some test files for aws csi feature
@liangxia Please help merge them.
=> Add aws csi test files

networking/multus-cni/Pods/multus-default-route-pod.yaml
@zhaozhanqi @huiran0826 @anuragthehatter @rbbratta
Please help to review, thanks!
=> Add multus-default-route-pod yaml

storage/azure-file/azurefile-clusterrole.yaml
Add: add yaml file according https://docs.openshift.com/container-platform/4.2/storage/dynamic-provisioning.html#azure-file-definition_dynamic-provisioning
=> Add: add yaml file for azure-file

storage/hostpath/security/hostpath.yaml
@liangxia Please help merge this pr.
=> Remove one container

scheduler/node-affinity/node-affinity-gt4-required-case14522.yaml, scheduler/node-affinity/node-affinity-required-case14479.yaml, scheduler/node-affinity/node-anti-affinity-required-exists-case14521.yaml
@xingxingxia  Please review and help merge. thanks.
=> replace with smaller image

fips/fips-master-disable.yaml, fips/fips-worker-disable.yaml
add fips disable test files for ocp-25822
=> add fips disable test files

olm/etcd-cluster-template.yaml, olm/etcd-subscription-template.yaml, olm/operatorgroup-template.yaml
As title, just add some templates for the OLM upgrading test.
=> add some templates to subscribe an operator

routing/openssl.conf
@liangxia please help review and merge. Thanks.
=> adding openssl.conf for creating custom csr and cert

storage/gce/security/gce-privileged-test.json, storage/gce/security/gce-selinux-fsgroup-test.json
=> Use image with SELinux for SELinux test

networking/ping_for_pod_containerPort.json
@pruan-rht Could you help merge this file? Thanks!
=> Add a file with opening container port

deployment/OCP-15153/deployment-example.yaml, deployment/OCP-15169/example-rs-annotation.yaml, deployment/OCP-15169/example-rs.yaml, deployment/hello-deployment-1.yaml, statefulset/hello-statefulset.yaml
@xingxingxia  Please help review and merge. thanks.
=> update for deployment and RS version

daemon/daemonset-negtive-never.yaml, daemon/daemonset-negtive-onfailure.yaml, daemon/daemonset-nodeselector.yaml, daemon/daemonset.yaml
update apiversion to apps/v1 for ocp 4.4.
@jhou1 PTAL
=> modify apiversion of daemonset to apps/v1

routing/operator/ingresscontroller-test.yaml, routing/operator/ingressctl-namespace-selector.yaml, routing/operator/ingressctl-route-selector.yaml, routing/operator/ingressctl-tls-custom.yaml, routing/operator/ingressctl-tls-intmd.yaml
=> update ingresscontroller file to add HostNetwork config

templates/OCP-11007/cakephp.json, templates/OCP-11007/cakephp1.json, templates/OCP-11007/cakephp3.json, templates/OCP-11007/cakephp4.json
@wzheng1  php:7.0 is not existed i n openshift, please help to merge it,thanks
=> Update php tag

networking/networkpolicy/nw_ipblock.yaml
[networking] add yaml for ipblock
=> [networking] add yaml for ipblock

scheduler/policy-label-presence-false.cfg, scheduler/policy-label-presence-true.cfg
@xingxingxia  Please help review and merge. thanks.
=> add policy for scheduler test

logging/clusterlogging/customresource-fluentd.yaml, logging/clusterlogging/customresource-fluentd_change.yaml, logging/clusterlogging/customresource-rsyslog.yaml
https://docs.openshift.com/container-platform/4.2/logging/config/cluster-logging-tolerations.html
=> Use same key as doc

cloud/cluster-autoscaler.yml, cloud/machine-autoscaler.yml
Update clusterautoscaler and machineautoscaler.
=> Update clusterautoscaler and machineautoscaler

configmap/pod-configmap-path.yaml
Update Deployment API version to apps/v1.
=> Update Deployment API version

storage/misc/pod-with-security-context.yaml
To support OCP-28093/28095/28097
=> Add pod with securityContext

deployment/vul_deployment.yaml
@yapei  No need the second deployment I just realized. please help to merge, thx
=> update test file

logging/clusterlogging/example-retentionPolicy.yaml
@anpingli could you please help merge it? thanks.
=> add new clusterlogging instance file with retentionPolicy

scheduler/policy_servicespreadingpriority.json
Add policy_servicespreadingpriority.json file for scheduler tests
=> Add policy_servicespreadingpriority.json

scheduler/policy_empty.json
Adding file policy.json and policy_empty.json to test OCP-12518
=> Add file policy.json and policy_empty.json

logging/logforwarding/rsyslog/insecure/rsyslogserver_configmap.yaml, logging/logforwarding/rsyslog/insecure/rsyslogserver_deployment.yaml, logging/logforwarding/rsyslog/insecure/syslog.conf, logging/logforwarding/rsyslog/insecure/syslog_buffered.conf, logging/logforwarding/rsyslog/rsyslogserver_svc.yaml, logging/rsyslogserver/02_creatersyslogserver.sh
=> add files to deploy rsyslog server

scheduler/priority-preemptionscheduling/podh.yaml, scheduler/priority-preemptionscheduling/podl.yaml, scheduler/priority-preemptionscheduling/podm.yaml, scheduler/priority-preemptionscheduling/priorityh.yaml, scheduler/priority-preemptionscheduling/priorityl.yaml, scheduler/priority-preemptionscheduling/prioritym.yaml
Add yaml files which are necessary to create priority class and pods using those priority classes.
=> Add files for priority scheduling

olm/art-secret-template.yaml, olm/operatorsource-template.yaml, olm/subscription-template.yaml, olm/tsb-cr-template.yaml
Add some templates for the OLM operators.
=> Add templates for marketplace component

scheduler/pod_ocp12489.yaml, scheduler/policy_leastrequestedpriority.json
Adding file to test leastrequestedpriority
=> Add file for leastrequestedpriority policy

logging/clusterlogging/clusterlogging-storage-template.yaml
@anpingli I'm going to simplify the scenario `Elasticsearch using dynamic volumes`, I want to use this template file to create the clusterlogging instance. PTAL, thanks.
=> add a clusterlogging template

olm/csc-template.yaml
Add the `CatalogSourceConfig` template for marketplace.
=> Add CSC template

scheduler/pod_ocp24240.yaml
Add pod.yaml fie for test OCP-24240
=> Add pod file for test OCP-24240

scheduler/policy-label-presence-false.json, scheduler/policy-label-presence-true.json
@kasturinarra @xingxingxia  Could you please help review , thanks.
=> update policy for scheduler test

cloud/priority-class-high.yml, cloud/priority-class-low.yml
Add PriorityClass files for OCP-19898. @jhou1  please help to take a look.
=> add PriorityClass file

README.md
@jhou1 @wsun1 @xltian  Could you help merge the PR, then move the repo to readyonly ?
=> Deprecate the repo
