openshift-qe/v3-testfiles

- persistent-volumes/nfs/pv-template.json
- persistent-volumes/nfs/pvc-template.json
Automation does not clean-up the PVs which is created via template, add labels for easier clean-up in our steps.
> add labels for easy cleanup

- persistent-volumes/misc/scc.yml
using '*' instead of listing all kinds of volumes. We do not need to update the volumes when they change. E.g, one supported volume kind added/removed.
> update scc volumes

- storage/s3/tc518929/config.yaml
currently the s3 creds are represented by a placeholder 'xxx', will need to replace them with actual value at runtime.
> config for tc518929

- online/tc531502/dotnet-sqlite-example-template.json
Add template file needed when auto case: https://tcms.engineering.redhat.com/case/531502/;
Just modify the default template "dotnet-sqlite-example", the image used by buildconfig is changed from "dotnet:latest" to "dotnet:1.0"
> add template file for tc531502, using image dotnet:1.0

- persistent-volumes/misc/pod.yaml
mountPath /tmp is too open and have different SELinux labels.
> Update mountPath for pod template

- build/stibuild-configchange.json
This change implements several things for TCMS case #497874:
- first, the case was failing in the Online environment, as the template pre/post deployment hooks did not contain a volume mount point, as such, docker tries to create a local volume, and is denied. To my knowledge, neither of these hooks are needed, and therefore removed.
- second, and for similar reasons above, the template did not contain a proper mysql mount, pv or pvc, and therefore those are added with this PR.
> Tcms497874 hotfix

- templates/OCP_11607/mysql-ephemeral-template.json
when testing https://polarion.engineering.redhat.com/polarion/#/project/OSE/workitem?id=OCP-11607 on online stage preview, The pod will be never created because the image is missing with version 5.7, created the copy of the template and changed the tag from 5.7 to latest.
> Working template for testcase OCP-11607

- pods/permission-data/dapi-keys-permission-pod.yaml
In online failed with: http://ci-qe-openshift.nay.redhat.com/userContent/cucushift/v3/2017/08/15/03:26:27/Permission_mode_work_well_in_privileged_policy_with_fsGroup/console.html
detail: http://pastebin.test.redhat.com/508352
> Update image for dapi-keys-permission-pod

- image/language-image-templates/OCP-13136/template.json
- image/language-image-templates/tc521461/template.json
- image/language-image-templates/tc521462/template.json
rails-ex repo has not supported below ruby 2.2 versions, so modify using this repo to ruby-ex repo.
> Modify source build code to ruby-ex for ruby:2.2 and ruby:2.0

- persistent-volumes/snapshot/snapshot-role.yaml
- persistent-volumes/snapshot/snapshot.yaml
Align the api change with upstream,
https://github.com/kubernetes-incubator/external-storage/blob/master/snapshot/doc/user-guide.md
> Update snapshot api to align with upstream

- routing/tc/tc477695/hello.json
- routing/tc/tc477695/new_route.json
Updating for https://github.com/openshift/cucushift/pull/5818 for Online env due to failure:
```
When I process and create "https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/routing/tc/tc477695/hello.json"
The Route "hello-route" is invalid: spec.host: Forbidden: you do not have permission to set the host field of the route
```
@yapei please merge, thanks
> Fix OCP-10602 host

- templates/OCP-11344/samplepipeline.yaml
- templates/tc531203/samplepipeline.json
Since the default configuare for slave node in jenkins are using v3.9 tag for release registry, it can't fetch before release. So modify the sample pipeline to use jenkins master.
> Change slave node to jenkins master

- logging_metrics/secure_heapster/heapster_grafana_influxdb.yaml
change cert-dir from /var/run/kubernetes to /tmp since /var/run/kubernetes is mounted as RO, so new generated cert can not be touched in the dir.
> Change cert-dir to for api-server

- build/tc517367/test-buildconfig.json
- build/tc517369/test-buildconfig.json
- build/tc517370/test-buildconfig.json
use ruby23 image as base image instead of ruby20, due to ruby-hello-world repo does not support ruby2.0 any more
> update buildconfig template

- persistent-volumes/security/privileged-test.json
- persistent-volumes/security/selinux-fsgroup-test.json
Copied from https://github.com/openshift-qe/v3-testfiles/tree/master/persistent-volumes/gce/security
and updated
```
"volumes": [
{
"name": "gcepd",
"gcePersistentDisk": {
"pdName": "my-data-disk",
"fsType": "ext4"
}
}
],
```
to
```
"volumes": [
{
"name": "myvolume",
"persistentVolumeClaim": {
"claimName": "myclaim"
}
}
],
```
> Security test which use pvc, instead of volume directly

- storage/snapshot/ClusterRole-controller.yaml
@jhou1  
Tested v1beta1 on 3.7/3.10/3.11, both works.
> Lower api version to support 3.7

- image/gitserver/gitserver-ephemeral.yaml
- image/gitserver/gitserver-persistent.yaml
gitserver tree has been removed from origin repo, but we still need use these files in automation
> Add gitserver test files

- build/ruby20rhel7-template-docker.json
- build/ruby20rhel7-template-sti.json
- build/ruby22-imageupgrade-stibuild.json
- build/ruby22rhel7-env-sti.json
- build/ruby22rhel7-template-docker.json
- build/ruby22rhel7-template-sti.json
- build/tc470422/application-template-stibuild.json
- build/tc476354/pushimage.json
- build/tc479297/test-template-dockerbuild.json
- build/tc482273/test-template-stibuild.json
- templates/OCP-11417/ruby22rhel7-template-sti-wrong-source.json
- templates/OCP-11417/ruby22rhel7-template-sti.json
- templates/OCP-12057/application-template-stibuild_pull_private_sourceimage.json
- templates/tc479059/application-template-parameters.json
- templates/tc515804/application-template-stibuild.json
- templates/tc517666/ruby22rhel7-template-sti.json
- templates/tc517667/ruby22rhel7-template-sti.json
- templates/tc517668/ruby22rhel7-template-docker.json
- templates/tc531203/samplepipeline.json
- templates/ui/application-template-dockerbuild-without-customize-route.json
- templates/ui/application-template-dockerbuild.json
- templates/ui/application-template-stibuild-without-customize-route.json
- templates/ui/application-template-stibuild.json
Now in 4.0 version it's not support args in postcommit, so updated using script, and updated files works in 3.11 ....
> Updated postcommit to apply for 4.0 version

- networking/pod_with_udp_port_listener.json
This file is required for testing OCP-19810. This json file creates a pod with udp port listening in the user project with the help of ncat tool and have replicas value set to 1 to simulate recreation in case the pod gets deleted.
> Test file required for OCP-19810

- logging/clusterlogging/OCP-21311/catalogsorceconfig.yaml
- logging/clusterlogging/csc-clusterlogigng.yaml
- logging/clusterlogging/csc-elasticsearch.yaml
- metering/OLM_examples/metering-catalogsourceconfig.yaml
@pruan-rht  @QiaolingTang 
Change group/version of OperatorSource/CatalogSourceConfig to operators.coreos.com/v1 from marketplace.redhat.com/v1alpha1
Reference to http://post-office.corp.redhat.com/archives/aos-devel/2019-March/msg00580.html
> Group and version changes of Marketplace APIs

- storage/misc/storageClass-noProvisioner.yaml
Also checked in verification-tests and cucushift, there is only one reference to the changed file, which is desired.
> Update the storage class name to a non-common one

- storage/iscsi/pod-two-luns.json
Test file storage/iscsi/pod-two-luns.json is only used by test case OCP-10143, which does not do securityContext check.
```
$ pwd
/home/lxia/github.com/verification-tests
$ grep -r 'iscsi/pod-two-luns' *
features/tierN/storage/iscsi.feature:    When I run oc create over "https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/storage/iscsi/pod-two-luns.json" replacing paths:
```
SecurityContext check for iSCSI is done in test case [OCP-9638](https://github.com/openshift/verification-tests/blob/master/features/storage/iscsi.feature#L4), which uses test file [pod.json](https://raw.githubusercontent.com/openshift-qe/docker-iscsi/master/pod.json) 
@jhou1 @weherdh @chao007
> Remove unused securityContext from OCP-10143

- dockerfiles/squid-proxy/latest/squid_auth.conf
Case OCP-11564 failed. https://bugzilla.redhat.com/show_bug.cgi?id=1663453#c1 pointed out the cause:
"internal proxies allow CONNECT on 8443 but don't seem to allow this on 6443"
So fixing it for the case. Pass log: job/Runner-v3/42623/console . @zhouying7780
> Add 6443 for squid proxy conf

- logging/clusterlogging/deploy_clo_via_olm/4.2/clo-sub-template.yaml
- logging/eleasticsearch/deploy_via_olm/4.2/eo-sub-template.yaml
@anpingli  PTAL
I'm adding these 2 files to make the automation test more flexible.
When launch job to run the automation test, no matter what the name of opsrc is and no matter which version of logging we want to test, we just need to set some env vars, e.g.:
```
export BUSHSLICER_CONFIG='                                                        
environments:
ocp4:
version: "4.3"
subscription_opsrc_name: "redhat-operators-art"
```
> adding subscription template files for logging automation testing

- templates/tc467937/pod467937-new.yaml
The case failed in our CI runs: [failure log](https://url.corp.redhat.com/ff3d1e4).
```
Given the pod named "kubernetes-metadata-volume-example" becomes ready
12:39:15 INFO> oc get pods kubernetes-metadata-volume-example --output=yaml ...
...
container create failed: container_linux.go:345: starting container process caused 
"process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/kubelet
/pods/461daf19-ffc9-11e9-b488-02cbe657c478/etc-hosts\\\" to rootfs \\\"/var/lib/containers/storage
/overlay/5e8480c5de374cbd32b63237b92307ec76856e7ca7f3510f0decb4f4bb3850ca/merged\\\" at
\\\"/var/lib/containers/storage/overlay/5e8480c5de374cbd32b63237b92307ec76856e7ca7f3510f0decb4f4bb3850ca/merged/etc/hosts\\\" 
caused \\\"open /var/lib/containers/storage/overlay …
```
> Fix OCP-16295 volume mount path cannot be system path /etc

- logging/logforwarding/elasticsearch/insecure/logforwarding-elasticsearch-insecure.yaml
- logging/logforwarding/elasticsearch/secure/logforwarding-elasticsearch.yaml
- logging/logforwarding/fluentd/insecure/logforwarding-insecure.yaml
- logging/logforwarding/fluentd/secure/logforwarding-secure.yaml
Per https://github.com/openshift/cluster-logging-operator/blob/master/pkg/apis/logging/v1alpha1/forwarding_types.go#L47, change the `inputType` to `inputSource`
@anpingli PTAL, thanks.
> change inputType to inputSource

- storage/cinder/security/cinder-selinux-fsgroup-test.json
@chao007 @duanwei33 
Failure [log](http://ci-qe-openshift.usersys.redhat.com/userContent/cucushift/v3/2020/01/10/05:15:39/origin_infra_20_volume_security_testing-cinder-volumeID-cinder/console.html)
> Use image with SELinux for cinder SELinux test

- svc-catalog/ups-broker-template.yaml
Change the deployment api to apps/v1 since the extensions/v1beta1 no longer useful in OCP 4.4
> modify the api of deployment to apps/v1

- storage/subpath/iscsi-subpath.json
Fix automation of OCP-18408, invalid option -- Z to command ls as the image does not have SELinux.
> Use image with SELinux

- cloud/local-storage-pod.yml
Auto "OCP-24715- Cluster-autoscaler should never delete nodes with pods with local storage" will use this file. @jhou1 Please help to take a look.
> add local storage pod

- scheduler/priority-preemptionscheduling/podh.yaml
- scheduler/priority-preemptionscheduling/podl.yaml
- scheduler/priority-preemptionscheduling/podm.yaml
The parameters set before for memory & cpu does not allow to get the pod into terminating state. So changing those params now
> Modifying files to set right params

- scheduler/pod_ocp12489.yaml
Image does not work when a normal user creates a pod using the yaml file, so changing the image name here.
> Changing the image name to work with normal user

- networking/iperf_nodeport_service.json
We need TCP port for control connection and UDP port for
testing packet loss
use auto nodePort, OpenShift will complain about the service
using the same port or something, but it works having both
UDP and TCP in the same service
Used for OVN tests:
https://github.com/openshift/verification-tests/pull/767
> add iperf_nodeport_service exposing both TCP and UDP ports

- cloud/autoscaler-auto-tmpl.yml
- cloud/job-work-q.yml
Update sleep time to 3000. 
Sometimes we got bellow error, from the log we can see autoscaler scale down automaticly before we delete payload. Workload pod is in Completed status. Increase sleep time to make sure pod are in running status. @jhou1 @miyadav Please help to take a look.
```
[07:42:21] INFO> Exit Status: 0
Machineset machineset-clone-20108-2 has 3 running machines, expected 2 (RuntimeError)
/home/sunny/code/verification-tests/features/step_definitions/machine_set.rb:56:in `/^the machineset should have expected number of running machines$/'
I0319 07:36:18.245507       1 scale_up.go:274] 8 other pods are also unschedulable
I0319 07:36:18.250258       1 scale_up.go:431] Best option to resize: openshift-machine-api/machineset-clone-20108-2
I0319 07:36:18.250289       1 …
```
> update autoscaler job

- storage/security/emptydir_selinux.json
Summit new file with one container due to the ports conflict if there are two containers.
> [OCP-9698] Update the selinux checking pod
